### ISSUE TITLE
parameters for Music Transformer

### ISSUE THREAD

**Issue by inventor71** [magenta/magenta#1491]
When training music transformer, to use the relative attention function 
the self_attention_type should be set to dot_product_relative_v2,
but then, we should specify max_relative_position. I'm curious what would be a good 
number for this, if I want to reproduce the quality result on magenta blog.
Also, I want to know if using the base_transformer and the predefined PROBLEM, score2perf_maestro_language_uncropped_aug, is the right way in using relative attention function.

```
HPARAMS_SET=score2perf_transformer_base
MODEL=transformer
PROBLEM=score2perf_maestro_language_uncropped_aug

HPARAMS=\
"label_smoothing=0.0,"\
"max_length=0,"\
"self_attention_type=dot_product_relative_v2,"\
"max_relative_position=1024,"\
"max_target_seq_length=2048"
```

I trained 1000000 epchs using the parameters above, but it gave worse result than the initial model given score2perf README. I wonder if i am setting some parameter wrong or if i am missing something.

**Comment by inventor71** [comment]
i'm still stuck on training the Music Transformer with relative attention. 
Can you please elaborate more on how to use the `self_attention_type=dot_product_relative_v2` flag and its parameters on training? It is not so clear for me, switching from the transformer baseline to the TF with relative global attention (as in the Music Transformer paper)

**Comment by 00001101-xt** [comment]
@inventor71 Hi, have you figured out the `hparams` if `self_attention_type=dot_product_relative_v2`?

Thanks.

**Comment by inventor71** [comment]
> @inventor71 Hi, have you figured out the `hparams` if `self_attention_type=dot_product_relative_v2`?
> 
> Thanks.

It's been a while since I last looked into ai-based music. Sorry I couldn't provide you a lot of help. 
I'm closing the issue now.
