### ISSUE TITLE
NoteSequence not picklable

### ISSUE THREAD

**Issue by cifkao** [magenta/magenta#1733]
The `NoteSequence` proto is not picklable, which is a nuisance when you want to use it in parallel/distributed processing. However, it seems that some protobuffers (e.g. `tf.GraphDef`) can be pickled, so I guess it's just a matter of using a more recent version of protoc or passing the right flag to it?

The pickle error is:
```
PicklingError: Can't pickle <class 'music_pb2.NoteSequence'>: import of module 'music_pb2' failed
```

**Comment by adarob** [comment]
Please reopen in https://github.com/magenta/note-seq.
