### ISSUE TITLE
Inconsistent transcription results on notebook and local transcription

### ISSUE THREAD

**Issue by avikj** [magenta/magenta#1738]
I am trying to run MIDI transcription on piano recordings from my iPhone. The MIDI output has notes all over the place, like the image below.

![image](https://user-images.githubusercontent.com/10556549/83701194-bdcdbb00-a5bd-11ea-86ce-7857de7b7ca0.png)

The online Piano Scribe tool works well on the same recording, giving these results
![image](https://user-images.githubusercontent.com/10556549/83701264-fcfc0c00-a5bd-11ea-97ba-8c17beb04253.png)

I am using the latest checkpoint to transcribe locally, and in both cases I used a WAV file. Voice memos on my iPhone gave a m4a which I converted to WAV using ffmpeg.

Additionally, the model gives good results when I transcribe audio pulled from professional recordings on YouTube. 

Why are the results so much worse when I transcribe the same audio locally vs. on Piano Scribe? Is there some sort of pre-processing done to remove noise on the web application?

For reference, here is the audio file I transcribed: https://drive.google.com/file/d/1YMk1f4qYrb5go-jGCWZsgEhbnIcCXOR6/view?usp=sharing

**Comment by avikj** [comment]
I additionally transcribed the same audio file in the Onsets and Frames Colab Notebook using the MAESTRO model and got good results:
![image](https://user-images.githubusercontent.com/10556549/83956245-a5a1aa00-a810-11ea-9c3f-aac8f91feeef.png)

Is there some hyperparameter I may be missing? Or does the model checkpoint used in the Colab notebook differ from the one linked in the current README?

**Comment by avikj** [comment]
I figured out the issue, I had switched over to a different directory and was passing in a non-existent directory for `model_dir`. As a result I was running a model with random weights. This should output an error message if `model_dir`doesn't exist or is invalid.

**Comment by cghawthorne** [comment]
Glad you were able to figure it out! Feel free to submit a PR for the error message you suggested.
