### ISSUE TITLE
Generating Piano Music with Transformer for colab bug..

### ISSUE THREAD

**Issue by James1liu** [magenta/magenta#1740]
I try the Link is follow 
https://colab.research.google.com/notebooks/magenta/piano_transformer/piano_transformer.ipynb

when I try this tip(Setup and Load Checkpoint)
I got Error 

**ValueError                                Traceback (most recent call last)
<ipython-input-3-9665ca3fb846> in <module>()
     53 
     54 # "Burn" one.
---> 55 _ = next(unconditional_samples)**

Then I found (ckpt_path = '/content/checkpoints/unconditional_model_16.ckpt') is disappear

and also  found (!gsutil -q -m cp -r gs://magentadata/models/music_transformer/* /content/) 
this command cant not found

some one have this file (unconditional_model_16.ckpt) to help me!!

Thanks!

**Comment by iansimon** [comment]
I'm not seeing either of those issues.  Can you restart the runtime and try again?

**Comment by adarob** [comment]
Hi @James1liu. It looks like the Colab version is a bit behind. Can you try adding the line `%tensorflow_version 1.x` to the top of the `Environment Setup` cell?

While I haven't seen exactly that issue you mentioned, I don't expect the Colab to work correctly without that line.

**Comment by James1liu** [comment]
Dear Both,

I try restart runtime and set **%tensorflow_version 1.x** to the top of the Environment Setup cell.
And It's work!! Thanks @adarob ,

This problem has troubled me for three days..

Thanks..
