### ISSUE TITLE
'Not found: Op type not registered 'LSTMBlockCell' in binary running on ...'

### ISSUE THREAD

**Issue by JesseBerdowski** [magenta/magenta#1744]
Version: Tensorflow 1.13.1
Build Tensorflow from source: Yes
Written Custom code:No, literal copying of the model

Hi guys,

I am trying to implement the music_vae model in c++. I managed to import the frozen model. But when I try to add the graph to the session, I receive the following error:

Not found: Op type not registered 'LSTMBlockCell' in binary running on DESKTOP-0K8OMI1. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
Press any key to continue . . .

I have tried several approaches,, most noteworthy the solution as proposed in https://github.com/tensorflow/tensorflow/issues/11847. Unfortunately, without any results. Do you know a solution to this issue? I am guessing you had to use a similar approach when uilding the java API. 

Kind regards,

Jesse Berdowski

**Comment by adarob** [comment]
I have not tried to run MusicVAE in C++. Have you tried what is suggested in that error message? LSTMBlockCell is in tf.contrib.rnn in TF v1.

I think it might actually be best to post this issue to TensorFlow since it seems to be a more general issue.

**Comment by JesseBerdowski** [comment]
thank you kindly for your answer
