### ISSUE TITLE
Cannot convert checkpoint to pb file

### ISSUE THREAD

**Issue by minhtu14** [magenta/magenta#1745]
Hi team,

I'm going to convert "On Set And Frame" check point to pb file but i met an issue that 
KeyError: "The name 'onsets/cudnn_lstm/opaque_kernel_saveable' refers to an Operation not in the graph."

this is my code that I have used covert it :
`with tf.Session() as sess:
   # Restore the graph
    saver = tf.train.import_meta_graph(meta_path, clear_devices=True)
    #saver = tf.train.Saver(max_to_keep=5)
    # Load weights
    saver.restore(sess,tf.train.latest_checkpoint('maestro_checkpoint/train'))

    # Freeze the graph
    frozen_graph_def = tf.graph_util.convert_variables_to_constants(
        sess,
        sess.graph_def,
        output_node_names)

    # Save the frozen graph
    with open('output_graph.pb', 'wb') as f:
      f.write(frozen_graph_def.SerializeToString())`
My goal is want to convert it to frozen graph after then from pb file I can convert to tflite run it to my device.
Could you help me ?

OS: win 10
tensorflow : v1.1.14
python: v3.7

**Comment by adarob** [comment]
You need to remove all of the `.*opaque_.*` variables since they are only used during training with cudnn. 

See https://stackoverflow.com/questions/41621071/restore-subset-of-variables-in-tensorflow for examples of how to restore only a subset of the variables.
