### ISSUE TITLE
Music VAE - Experiences with extension of TriadChordOneHotEncoding

### ISSUE THREAD

**Issue by AI-Guru** [magenta/magenta#1754]
Hello!

One feature of Music VAE that I fell in love with recently is the ability to condition the generation part to chords. Here we can use the basic four triads (major, minor, augmented, diminished) to steer what performance is generated.

Were there any experiments with an extended set of chords that went way beyond the four basic triads?  Is there some implementation somewhere?

**Comment by iansimon** [comment]
We have another chord encoding here that can handle an extended set of chords: https://github.com/magenta/note-seq/blob/master/note_seq/chords_encoder_decoder.py#L139

However, as it's not a one-hot encoding it'll be a little awkward (but certainly possible) getting it to work with the current MusicVAE codebase.  We do have a pretrained RNN model that uses it, though: https://github.com/magenta/magenta/tree/master/magenta/models/improv_rnn#chord-pitches-improv

More recently, we have extended MusicVAE to work with chord + key conditioning, which isn't quite what you asked but is sort of in the same direction, e.g. in the key of C a G major chord is likely to be dominant.
