### ISSUE TITLE
install errors with pip

### ISSUE THREAD

**Issue by lonce** [magenta/magenta#1757]
Hi,
   I am getting some errors during the pip installs (on Ubuntu 18.04): 

> ERROR: gym 0.17.2 has requirement cloudpickle<1.4.0,>=1.2.0, but you'll have cloudpickle 1.5.0 which is incompatible.
> ERROR: tensor2tensor 1.15.7 has requirement tensorflow-probability==0.7.0, but you'll have tensorflow-probability 0.10.0 which is incompatible.
> ERROR: tensorflow 2.2.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.0 which is incompatible.

This happens with
> pip install magenta

and also installing locally after downloading source from github and running

> pip install -e .

In both cases, the installation proceeds to completion, and the code seems to run OK (training GANSynth). Maybe the dependency specs are just stricter than they need to be (tensorflow 2.2.0 probably runs fine with scipy 1.5)? 

Thanks,

**Comment by adarob** [comment]
Yes, they are too strict on those other packages. Unfortunately we don't control their requirements so we just have to ignore until they update.
