### ISSUE TITLE
Need help on SVG VAE's data generation

### ISSUE THREAD

**Issue by chunchet-ng** [magenta/magenta#1759]
HI there,

Can you provide the code to transform fonts in .ttf format to parquetio database format as stated in the data generation part of this repo [svg_vae](https://github.com/magenta/magenta/tree/master/magenta/models/svg_vae).

Also, can you list out what libraries are used to extract such information based on the ttf file, is it fontforge?

Any help/suggestions are welcomed.

Thank you in advance

**Comment by hardmaru** [comment]
Let's see if @iRapha can help with this one.

**Comment by iRapha** [comment]
Thanks for the question! 

When we started the project, we already had the parquetio database in the format described. The work of collecting fonts (originally in .ttf, and other formats) and converting them to sfd to populate the parquetio was done before we started this project. I know that effort used fontforge to make this conversion, but unfortunately the exact code we used no longer exists.

Hope this is useful!

**Comment by chunchet-ng** [comment]
> Thanks for the question!
> 
> When we started the project, we already had the parquetio database in the format described. The work of collecting fonts (originally in .ttf, and other formats) and converting them to sfd to populate the parquetio was done before we started this project. I know that effort used fontforge to make this conversion, but unfortunately the exact code we used no longer exists.
> 
> Hope this is useful!

Thank you for your reply. If the data generation code is unable, will you consider to release the dataset used for this work?

**Comment by iRapha** [comment]
The code for generating the processed dataset from the parquetio (containing fonts in SFD, a common font file format) is in the [svg vae repository](https://github.com/magenta/magenta/tree/master/magenta/models/svg_vae).

The code for generating the parquetio's SFD from .ttf files should be straightforward to implement with fontforge.

Unfortunately, we are unable to release the processed dataset or the parquetio in their raw formats.

**Comment by joanrod** [comment]
@chunchet-ng Did you make it work in the end?
Thanks
