### ISSUE TITLE
⚠️A need for a user-friendly Google Colabs ⚠️ Issues with existing Colabs⚠️

### ISSUE THREAD

**Issue by asigalov61** [magenta/magenta#1774]
Hey guys, Magenta Team,

Thanks for the amazing models, especially Piano Transformer - its awesome and fun.

Now, I am sorry but there are some very serious issues with the main Google Magenta Colabs...

1) Piano Transformer Colab: 

a) Colab produces many env. setup errors and had to be executed twice or trice to fix it. Requires a fix on your end.
b) It requires TF 1 and even when it finally runs, it produces many warnings about depreciation and mismatch of versions. Please fix this or it will not work for long. Please update it to TF2 which you support.
c) The models for Piano Transformer are hidden and can't be viewed/downloaded. Why is it so? I really want to have a backup/local copy.

2) MusicVUE MultiTrack Colab
a) Barely works. Many env.setup and other minor errors/versions mismatch.
b) Useless because it has a very strange layout and interface. It also is not designed for any serious/real testing of any kind so I can't even assess if it is good or not. Can you make it like Piano Transformer Colab?
c) Please understand that users need a hassle-free/code-free/frustration-free Colabs. Is it really that hard for Magenta Team to do? Is it also hard to make Colabs useful and practical at the same time? 
d) What I personally need from MusicVUE collabs is Generation from Scratch option, Continuation Option, and I would be even happier if there was an interpolation option as well. All set up in a similar way preferably as the Piano Transformer Colab.
e) All of these issues are why many people, particularly musicians can't even try Magenta, let alone use it.

So my DIRECT QUESTION IS THIS: Can someone from Magenta Team take on fixing all of these problems? I am willing to help but I do not know Python/coding very well so I can only do minor things. However, I would be willing to assist anyway if Magenta Team cares and respects its work.

Creating shitty Colabs like 2 for MusicVUE isn't cool, guys! It's not that hard to make a nice Colab, why is it not done or done haphazardly!!!

I am so tired and fed-up with having to spend 1/2 of my time with Magenta fixing code and getting really frustrated due to not working/useless Colabs.

So please, if you care and if you respect your work, fix/redo the main Colabs. I would be forever grateful for that kind of help. And your work would be useful and helpful for myself and other non-experts/users.

Thank you and stay safe/well 👍

**Comment by adarob** [comment]
Please reconsider how you are addressing people who have put a lot of work into this project, and open a new issue with more respectful language.

**Comment by adarob** [comment]
Also, if you're looking for easier-to-use interfaces targeted at musicians instead of researchers, please see g.co/magenta/studio.

**Comment by asigalov61** [comment]
@adarob Adam, this is not cool at all. And it is very disrespectful. No wonder Colabs do not work. 

But thank you so much for these clarifications because now I know exactly what to do.
