### ISSUE TITLE
 generate the eval_train tfrecords (for custom dataset)

### ISSUE THREAD

**Issue by jhlusko** [magenta/magenta#1781]
When registering a new dataset in configs.py, does there need to be an entry for eval_train? Where do we create the eval_train tfrecord?

The onsets_frames_transcription_create_tfrecords.py says

Usage:
onsets_frames_transcription_create_tfrecords \
  --csv="/path/to/dataset.csv" \
  --output_directory="/path/to/output" \
  --num_shards="0" \
  --wav_dir="/path/to/dataset/audio" \
  --midi_dir="/path/to/dataset/midi" \
  --expected_splits="train,validation,test"

Should the --expected_splits also include eval_train? How do we generate the eval_train tfrecords?

The eval_train tfrecords seems to be used as the test examples for onsets_frames_transcription_infer. Where are the test and validation tfrecords created by the dataset creation tool used? Is this documented? I am unclear about the process.

Thank you!

**Comment by cghawthorne** [comment]
eval_train is certainly not required. The purpose of that dataset is just as a "debugging" evaluation to make sure the model is actually fitting the training dataset. The dataset is generated from the 'train' split (as you can see from the 'maestro' example in configs.py), it's just done with `process_for_training=False`, which means the training data won't be split into smaller chunks and won't have any audio augmentation or other modification done to it.
