### ISSUE TITLE
Colab notebook error

### ISSUE THREAD

**Issue by AmitMY** [magenta/magenta#1787]
From https://magenta.tensorflow.org/demos/colab/

you point out to 
Play with Music Transformer and control the model in a few different ways, or just generate new performances from scratch.

https://colab.research.google.com/notebooks/magenta/piano_transformer/piano_transformer.ipynb

But the `Setup Environment` cell fails

**Comment by iansimon** [comment]
This should be fixed by #1775, but it won't take effect until the next release of the magenta pip package.  For now, if you just run that Setup Environment cell again it should work.
