### ISSUE TITLE
KeyError: 'tfds_data_dir'(GANSynth)

### ISSUE THREAD

**Issue by YB-Joe** [magenta/magenta#1800]
Hi, I got this error on GANSynth demo colab . How can I resolve it?

![image](https://user-images.githubusercontent.com/43649503/91554417-0a7d2400-e96a-11ea-9905-893c535b196a.png)

**Comment by PRamoneda** [comment]
I have the same problem

**Comment by jamesliu** [comment]
> I have the same problem

Same here

**Comment by ksunw0209** [comment]
Same... Does anybody know how to fix it?

**Comment by adarob** [comment]
I cannot reproduce this error. Instead I get a different error: 

`AttributeError: 'PrefetchDataset' object has no attribute 'make_initializable_iterator'`

I will put in a fix for this new error.

**Comment by ksunw0209** [comment]
I actually got the error above when I ran the colab demo on GANSynth. So I ran the code in Read.me using my local device which gave me the error in this thread.
Thank you.

**Comment by adarob** [comment]
Which line in the README gave you this error?

**Comment by ksunw0209** [comment]
`gansynth_generate --ckpt_dir=/path/to/acoustic_only --output_dir=/path/to/output/dir --midi_file=/path/to/file.mid`
I bet it's similar with this one: https://github.com/magenta/magenta/issues/1794
I pip installed gansynth, and it gave me this error.

**Comment by adarob** [comment]
@jesseengel FYI

Yes, this is an unfortunate issue where the model restoration requires the train dataset to be loaded. Rather than refactoring this legacy code, I created #1851 a bandaid.

**Comment by ksunw0209** [comment]
Aha... thank you. Does the colab demo have to work now? I still get the following error.
`AttributeError: 'PrefetchDataset' object has no attribute 'make_initializable_iterator'`
Plus there is an additional version error.
`ERROR: kfac 0.2.3 has requirement tensorflow-probability==0.8, but you'll have tensorflow-probability 0.11.0 which is incompatible.
ERROR: tensor2tensor 1.15.7 has requirement tensorflow-probability==0.7.0, but you'll have tensorflow-probability 0.11.0 which is incompatible.`

**Comment by adarob** [comment]
You can ignore the version error. The Colab will work again once #1850 is in and we push the new pip package. Probably later today.

**Comment by ksunw0209** [comment]
Thank you so much:) Keep up the great work! 👍
