### ISSUE TITLE
How are frame-based scores calculated in "onsets and frames" in the code?

### ISSUE THREAD

**Issue by guardian2020** [magenta/magenta#1807]
HI! I'd like to know whether in the code, the frame-based pitches are reported every 10 ms.

I ask this because in the paper, the frame-based scores are evaluated by reference [2], and reference [2] refers that the pitches are reported every 10 ms.

However, in the code (branch 9885adef56, which corresponds to the paper), in the function_get_eval_metrics() in the train_util.py, I didn't see information related to 10ms.

Anyone knows about this?

**Comment by cghawthorne** [comment]
You're correct, we just use the same frame size as what the model outputs (32ms). I actually hadn't noticed the reference to the 10ms size in that paper before now, so perhaps we should have done something different here.

For the papers we were comparing against, it's not totally clear if they used the 10ms or 32ms frame size for comparison. In any case, as we argue in the paper I think the Note F1 score is a much more important comparison, and that metric isn't tied to frame size.

**Comment by guardian2020** [comment]
Thank you so much for your reply, really very clear!
Just to make sure my understanding is right or not, I'd like to further ask whether the frame-based metrics in Table 1 in the paper is calculated by the lines of 285~290 and 387~394 in _get_eval_metrics() in train_util.py when running onsets_frames_transcription_train.py with the parameter being "eval" and dataset used being the test-split of MAPS dataset created by onsets_frames_transcription_create_dataset.py.
Sorry for taking up your time and thank you!

**Comment by cghawthorne** [comment]
The metrics in the paper all come from the infer script, which we ran after training was complete. The frame metrics end up being calculated in infer_util.py, look in `define_metrics`.

**Comment by guardian2020** [comment]
> The metrics in the paper all come from the infer script, which we ran after training was complete. The frame metrics end up being calculated in infer_util.py, look in `define_metrics`.

Thank you so much! I'm sorry that I have just seen your reply, because I have earlier updated a question related to this. I'll read carefully infer_util.py.
