### ISSUE TITLE
A portion at the beginning of the train hard to interpret

### ISSUE THREAD

**Issue by guardian2020** [magenta/magenta#1813]
Hi!
I'm trying to replicate "ONSETS AND FRAMES" branch 9985adef56. When I view the results with Tensorboard, while the whole training process and the result seemed normal and much good, I found a portion in the very beginning of the training process.
For the frame-based predictions:
First, recall
![image](https://user-images.githubusercontent.com/70155533/92335105-15376780-f094-11ea-9392-3bf40ab095ab.png)
If zooming in at the beginning protion, recall at the first checkpoint is larger than 0, from the second checkpoint on the recall suddenly went to 0 and remained 0 for 3 checkpoints.
![image](https://user-images.githubusercontent.com/70155533/92335183-08ffda00-f095-11ea-9fe0-a9e80504f761.png)
Ane then, precision has the similar scene, but much slighter:
![image](https://user-images.githubusercontent.com/70155533/92335176-fbe2eb00-f094-11ea-996b-9e0c851fa51c.png)
![image](https://user-images.githubusercontent.com/70155533/92335188-187f2300-f095-11ea-89cb-5397d61e0fc4.png)

For the metric of onset_note_precision: the value jumps from 0 to almost 1 from the previous checkpoint to the next one.
![image](https://user-images.githubusercontent.com/70155533/92335295-2bdebe00-f096-11ea-95a2-c7a42abfb8f9.png)
![image](https://user-images.githubusercontent.com/70155533/92335305-37ca8000-f096-11ea-9c89-bcd79e539102.png)

Despite that I checked the final (after 40k steps) training result with an inferring process (using onsets_frames_transcription_infer.py), which indicated the trained model worked very well, I still find it hard to interpret.

Anyone who knows about this?

Thanks!

**Comment by cghawthorne** [comment]
I think what's happening here is that when the model is first initialized, it's making essentially random frame predictions, which results in a lot of note predictions, but most of them are wrong. The model then quickly learns that most frames do not have active notes, so note predictions drop to near zero. After that, you see it start to learn to actually recognize notes.

**Comment by guardian2020** [comment]
Thank you very much for your reply. I'm very sorry for this so late reply, because of a busy period in last month.

It's still a bit difficult for me to understand that the "valley" of the recall and precision just after the training has started was **completely** zero (not nearly zero).
And this pattern seems to repeat each time a new training begins.

Could you please give me some intuition about this?

And has this phenomenon anything to do with the truncated_length, which has been set to 500 (original value is 1500, commented by 48s)? 

Thank you again!

**Comment by cghawthorne** [comment]
I haven't really done in-depth analysis for what's going on in the first steps of training. If you want to know exactly what's happening, I think the best thing to do would be to run inference using a checkpoint from that period and take a look at what the model is predicting for some sample files.
