### ISSUE TITLE
RuntimeError: models/my_ssd_resnet50_v1_fpn/ckpt-23.data-00000-of-00001; No such file or directory

### ISSUE THREAD

**Issue by mjf2004** [magenta/magenta#1820]
Good morning I'm running on google collaborate the training of a model, tensorflow 2 and api object detection. It ran and stopped a few times because google colab disconnects from the notebook and I have to reconnect, but even every time the training continued where it left off. And now I have the message below:

RuntimeError: models/my_ssd_resnet50_v1_fpn/ckpt-23.data-00000-of-00001; No such file or directory

I tried to search all the directories for these files that you don't find, but there is no such file.

follow images:

first: error
second: files on path within google colab "models/my_ssd_resnet50_v1_fpn/"
third: file checkpoint on "models/my_ssd_resnet50_v1_fpn/"

![colab-error](https://user-images.githubusercontent.com/71648038/93770939-3d29dd80-fbf3-11ea-8a54-b620acdc494c.JPG)
![path-](https://user-images.githubusercontent.com/71648038/93770957-431fbe80-fbf3-11ea-909d-00e1029e4ade.JPG)
![chk](https://user-images.githubusercontent.com/71648038/93787342-c0a0fa00-fc06-11ea-972c-fb506e204e67.JPG)

**Comment by cghawthorne** [comment]
Can you clarify which Magenta project this question is about?

**Comment by mjf2004** [comment]
> Good morning I'm running on google collaborate the training of a model, tensorflow 2 and api object detection. It ran and stopped a few times because google colab disconnects from the notebook and I have to reconnect, but even every time the training continued where it left off. And now I have the message below:
> 
> RuntimeError: models/my_ssd_resnet50_v1_fpn/ckpt-23.data-00000-of-00001; No such file or directory
> 
> I tried to search all the directories for these files that you don't find, but there is no such file.
> 
> follow images:
> 
> first: error
> second: files on path within google colab "models/my_ssd_resnet50_v1_fpn/"
> third: file checkpoint on "models/my_ssd_resnet50_v1_fpn/"
> 
> ![colab-error](https://user-images.githubusercontent.com/71648038/93770939-3d29dd80-fbf3-11ea-8a54-b620acdc494c.JPG)
> ![path-](https://user-images.githubusercontent.com/71648038/93770957-431fbe80-fbf3-11ea-909d-00e1029e4ade.JPG)
> ![chk](https://user-images.githubusercontent.com/71648038/93787342-c0a0fa00-fc06-11ea-972c-fb506e204e67.JPG)
