### ISSUE TITLE
convert_dir_to_note_sequences // tensor2tensor // magenta version

### ISSUE THREAD

**Issue by AnasGhrab** [magenta/magenta#1826]
If I install the last versions of tensorflow (or 2.2.0) and magenta, and then try to convert midi files to TFrecords using the script convert_dir_to_note_sequences I get this error :

``
pkg_resources.ContextualVersionConflict: (tensorflow-probability 0.11.0 (/usr/local/lib/python3.8/dist-packages), Requirement.parse('tensorflow-probability==0.7.0'), {'tensor2tensor'})

What are the versions of of tensorflow / tensorflow-probability / gast / tensor2tensor) that I should use to get the script convert_dir_to_note_sequences working correctly ?

Thanks.

**Comment by AnasGhrab** [comment]
The problem was with my version of librosa.

**Comment by Brami01** [comment]
Excuse me, which version of librosa did you use?
