### ISSUE TITLE
Problem installing Magenta due to 'llvmlite' 

### ISSUE THREAD

**Issue by carlosholivan** [magenta/magenta#1833]
I am having problems with Magenta installation regarding to llvmlite package.

I run this command for installing Magenta:

```
pip install magenta
```
And I got the following error:

```
Installing collected packages: llvmlite, numba, pygtrie, mido, sk-video, python-rtmidi, librosa, note-seq, gast
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.33.0+1.g022ab0f
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Should I uninstall llvmlite manually and the try to reinstall Magenta?

**Comment by cghawthorne** [comment]
I would recommend setting up a conda environment (https://docs.conda.io/en/latest/miniconda.html) for magenta so you can install/upgrade dependencies without worrying about modifying your system-wide Python setup.
