### ISSUE TITLE
Compatibility fix for Python 3(infer_util.py)

### ISSUE THREAD

**Issue by guardian2020** [magenta/magenta#1834]
Hi!

I found some code for "Onsets and Frames" in infer.py  in branch 9885adef56 is not running due to the incompatibility of Python 3.

Specifically, the line "for metric_name, metric_value in metrics_to_values.iteritems():" is not working.

I changed it to "for metric_name, metric_value in metrics_to_values.items():" to make it run.

**Comment by cghawthorne** [comment]
It's very likely there are portions of that code that do not work with Python 3 because we were using Python 2 at the time. However, we can only provide support for the code at HEAD, which should be fully py3 compatible.
