### ISSUE TITLE
A question about the parameter "truncated_length"

### ISSUE THREAD

**Issue by guardian2020** [magenta/magenta#1835]
Hi!

I'm asking if anyone knows how the parameter truncated_length in model.py in the "Onsets and Frames" (branch 9885adef56) works.
It's a bit difficult for me to understand because there's another parameter min_length defined in onsets_frames_transcription_create_dataset.py.
Both parameters are used to truncate the data but in different stages. The parameter min_length is used in the function find_split_points() in onsets_frames_transcription_create_dataset.py for truncating the data (only for training). The parameter truncated_length is used in the function _provide_data() in data.py and is run (in each of the models train, eval, test) by train_util.py.

It seems the parameter truncated_length is used to truncated the input tensors loaded from the tfrecords, and the tensors in the tfrecords has been processed by a splitting operation using the parameter min_length. I don't know whether this understanding is right.

If it is right, how would the program truncate the audio(and it's transformed dataforms)/midi files for training and evaluation when I set the min_length (as its default value) to be 20 seconds, and set the truncated_length to be 500 (the default value is 1500, commented by 48s) in model.py?  I guess, when training, if there are segments truncated to the length of just 20s, these segments will further be truncated by pairs of 15s and 5s? Is that right?
If using the default value (1500) of truncated_length, does it mean this value will actually not work because it's larger than min_length?

Thanks!

**Comment by cghawthorne** [comment]
Yeah, I think your general understanding is correct. If the truncated_length is longer than the input tensors, they'll be padded to the correct length: https://github.com/magenta/magenta/blob/9885adef56d134763a89de5584f7aa18ca7d53b6/magenta/models/onsets_frames_transcription/data.py#L395
