### ISSUE TITLE
Compatibility fix for Python 3(onsets_frames_transcription_create_dataset.py)

### ISSUE THREAD

**Issue by guardian2020** [magenta/magenta#1836]
Hi!

I found segments of the code in the file onsets_frames_transcription_create_dataset.py in the branch 9885adef56 of "Onsets and Frames" doesn't seem to work under Python 3.

Specifically, the first place:

  with tf.python_io.TFRecordWriter(train_output_name) as writer:
    for pair in train_file_pairs:
      print(pair)

I changed it to:

    for pair in train_file_pairs:
      pair = list(pair)
      for i in range(len(pair)):
        pair[i] = pair[i].encode("raw_unicode_escape")
      print(pair)

Another place has the similar problem:

  with tf.python_io.TFRecordWriter(test_output_name) as writer:
    for pair in test_file_pairs:
      print(pair)

changed to

  with tf.python_io.TFRecordWriter(test_output_name) as writer:
    for pair in test_file_pairs:
      pair = list(pair)
      for i in range(len(pair)):
        pair[i] = pair[i].encode("raw_unicode_escape")
      print(pair)

**Comment by cghawthorne** [comment]
It's very likely there are portions of that code that do not work with Python 3 because we were using Python 2 at the time. However, we can only provide support for the code at HEAD, which should be fully py3 compatible.
