### ISSUE TITLE
Compatibility fix for Python 3 (onsets_frames_transcription_infer.py)

### ISSUE THREAD

**Issue by guardian2020** [magenta/magenta#1837]
Hi!

I found segments of the code in the file onsets_frames_transcription_infer.py in the branch 9885adef56 of "Onsets and Frames" doesn't seem to work under Python 3.

Specifically, the first place:

        filename = filenames[0].replace('/', '_').replace(':', '.')
        output_file = os.path.join(run_dir, filename + '.mid')

I changed it to:

        filename = filenames[0].replace(b'/', b'_').replace(b':', b'.')
        output_file = os.path.join(run_dir.encode('utf-8'), filename + b'.mid')

Similarly, the second place:

        label_from_frames_output_file = os.path.join(
            run_dir, filename + '_label_from_frames.mid')

changed to

            run_dir.encode('utf-8'), filename + b'_label_from_frames.mid')

The third place:

        label_output_file = os.path.join(run_dir, filename + '_label.mid')

changed to:

        label_output_file = os.path.join(run_dir.encode('utf-8'), filename + b'_label.mid')

The fourth place:

        pianoroll_output_file = os.path.join(run_dir,
                                             filename + '_pianoroll.png')
changed to:

        pianoroll_output_file = os.path.join(run_dir.encode('utf-8'),
                                             filename + b'_pianoroll.png')

The fifth place:

        with tf.gfile.GFile(pianoroll_output_file, mode='w') as f:

changed to

        with tf.gfile.GFile(pianoroll_output_file.decode(), mode='w') as f:

**Comment by cghawthorne** [comment]
It's very likely there are portions of that code that do not work with Python 3 because we were using Python 2 at the time. However, we can only provide support for the code at HEAD, which should be fully py3 compatible.
