### ISSUE TITLE
Will the evaluation results be the same using the "eval" mode of onsets_frames_transcription_train.py?

### ISSUE THREAD

**Issue by guardian2020** [magenta/magenta#1838]
Hi!

I'd like to ask will the evaluation results be the same if I use the "eval" mode of onsets_frames_transcription_train.py as using onsets_frames_transcription_infer.py?

Specifically, we changed two places in the source code:
the first change is in train_util.py

the original code

    tf.contrib.training.evaluate_repeatedly(
        train_dir,
        eval_ops=metrics_to_updates.values(),
        hooks=hooks,
        eval_interval_secs=60,
        timeout=None)

is replaced by

    import glob
    import os
    import re
    checkpoint_paths = glob.glob(os.path.join(train_dir, "model.ckpt-*.meta"))
    checkpoint_paths.sort(key = lambda filename : int(re.findall(r"\d+", filename)[-1]))
    for file_name in checkpoint_paths:
        checkpoint_path = file_name[0:-5]
        slim.evaluation.evaluate_once(
            master='',
            checkpoint_path=checkpoint_path,
            logdir=os.path.join(train_dir, "../eval"),
            eval_op=list(metrics_to_updates.values()))

The first change is made to support an evaluation after the training, instead of during the training (we don't have so much memory).

The second change when calculating note metrics, as the paper referred to (_"During inference, we restrict the predictions from the framewise detector by not allowing a new note to start unless the onset detector also agrees that an onset for that pitch is present in the frame"_) , we added the onsets. Specifically, in the original code in the function _note_metrics()

    est_sequence = pianoroll_to_note_sequence(
        predictions,
        frames_per_second=data.hparams_frames_per_second(hparams),
        min_duration_ms=hparams.min_duration_ms)

    ref_sequence = pianoroll_to_note_sequence(
        labels,
        frames_per_second=data.hparams_frames_per_second(hparams),
        min_duration_ms=hparams.min_duration_ms)

are changed to:

    est_sequence = pianoroll_to_note_sequence(
        predictions,
        frames_per_second=data.hparams_frames_per_second(hparams),
        min_duration_ms=hparams.min_duration_ms,
        onset_predictions=onset_predictions)

    ref_sequence = pianoroll_to_note_sequence(
        labels,
        frames_per_second=data.hparams_frames_per_second(hparams),
        min_duration_ms=hparams.min_duration_ms,
        onset_predictions=onset_labels)

And the related reference of this function is changed.

Will it be the same with onsets_frames_transcription_infer.py to use the "eval" mode of onsets_frames_transcription_train.py after made these two modifications?

**Comment by cghawthorne** [comment]
Related answer in #1839. I think you'll still need to use the code in infer.py so that it uses the entire example instead of a smaller chunk.
