### ISSUE TITLE
How to Enable TPU Acceleration?

### ISSUE THREAD

**Issue by nekologist** [magenta/magenta#1845]
Hi there, I need to train my model with a TPU on GCP, but I don't know how to enable TPU acceleration on magenta. Any ideas or solutions?

**Comment by nekologist** [comment]
Also the TPU model I want to use is TPU v3

**Comment by cghawthorne** [comment]
Which model are you wanting to train?

**Comment by nekologist** [comment]
> Which model are you wanting to train?

oh, I will train with `polyphony_rnn_train` command

**Comment by cghawthorne** [comment]
There are many models within the magenta repo. Unfortunately, polyphony_rnn does not support TPU training. You'll need to use either GPU or CPU.

**Comment by nekologist** [comment]
what about performance RNN?

**Comment by cghawthorne** [comment]
Unfortunately, no, it also does not support TPU training.

**Comment by nekologist** [comment]
ugh so is there any model that supports it?

**Comment by cghawthorne** [comment]
Yes, but it really is a on model-by-model basis. I'd suggest searching for "TPU" in our docs or code. For example, the Onsets and Frames Drums model has TPU training support documented here: https://github.com/magenta/magenta/tree/master/magenta/models/onsets_frames_transcription#training
