### ISSUE TITLE
How can i run Onsets Frames Transcription model on Android or iOS?

### ISSUE THREAD

**Issue by ekrmh** [magenta/magenta#1855]
Hi,

I would like to convert your pre-trained[ Onsets Frames Transcription](https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/maestro_checkpoint.zip) model to Tensorflow Lite model and use it on Android and iOS phones. 

I found some documents for [Python and JS](https://github.com/magenta/magenta/tree/master/magenta/models/onsets_frames_transcription) but i couldn't any information about mobile. I'm not sure that it is possible.

Is it possible?

Thanks

**Comment by cghawthorne** [comment]
We have some experimental TFLite versions available here: https://github.com/magenta/magenta/tree/master/magenta/models/onsets_frames_transcription/realtime
