### ISSUE TITLE
Web down

### ISSUE THREAD

**Issue by moracabanas** [magenta/magenta#1857]
I read [this](https://blog.tensorflow.org/2020/08/creating-sounds-of-india-with-tensorflow.html) article which leads to test it on [SondsofIndia](g.co/SoundsofIndia) and it seems down

**Comment by notwaldorf** [comment]
Yikes, thanks for pointing it out! Investigating what's up with it.

**Comment by notwaldorf** [comment]
Ah, it turns out that this was a limited project and only ran for a small amount of time. Sorry about that :( 
I'll reach out to the owner of the post to see if we can update the copy on that to make it more clear.
