### ISSUE TITLE
Magenta support for mac M1

### ISSUE THREAD

**Issue by zappos23** [magenta/magenta#1867]
Hi,

I am having issue when trying to install magenta on a mac M1. Only apple's  TensorFlow version '2.4.0-rc0' is supported for the M1. 

Dependency conflict with the TensorFlow version is causing the installation error. Can you please help? Thanks

The conflict is caused by:
    magenta 2.1.3 depends on tensorflow
    magenta 2.1.2 depends on tensorflow
    magenta 2.1.1 depends on tensorflow
    magenta 2.1.0 depends on tensorflow
    magenta 2.0.2 depends on tensorflow
    magenta 2.0.1 depends on tensorflow
    magenta 2.0.0 depends on tensorflow
    magenta 1.3.3 depends on tensorflow<2.0.0 and >=1.15.0
    magenta 1.3.2 depends on tensorflow<2.0.0 and >=1.15.0
    magenta 1.3.1 depends on tensorflow<2.0.0 and >=1.15.0
    magenta 1.3.0 depends on tensorflow<2.0.0 and >=1.15.0
    magenta 1.2.2 depends on tensorflow<2.0.0 and >=1.15.0
    magenta 1.2.1 depends on tensorflow<2.0.0 and >=1.15.0
    magenta 1.2.0 depends on tensorflow<2.0.0 and >=1.15.0
    magenta 1.1.8 depends on tensorflow<2.0.0 and >=1.14.0
    magenta 1.1.7 depends on tensorflow<2.0.0 and >=1.14.0
    magenta 1.1.6 depends on tensorflow>=1.14.0
    magenta 1.1.5 depends on tensorflow>=1.14.0
    magenta 1.1.3 depends on tensorflow>=1.13.0
    magenta 1.1.2 depends on tensorflow>=1.13.0
    magenta 1.1.1 depends on tensorflow>=1.12.0
    magenta 1.1.0 depends on tensorflow>=1.12.0
    magenta 1.0.5 depends on tensorflow>=1.12.0
    magenta 1.0.2 depends on tensorflow>=1.12.0
    magenta 1.0.1 depends on tensorflow>=1.12.0
    magenta 0.5.0 depends on tensorflow>=1.12.0
    magenta 0.4.0 depends on tensorflow>=1.12.0
    magenta 0.3.19 depends on tensorflow>=1.12.0
    magenta 0.3.18 depends on tensorflow>=1.12.0
    magenta 0.3.16 depends on tensorflow>=1.12.0
    magenta 0.3.15 depends on tensorflow>=1.12.0
    magenta 0.3.14 depends on tensorflow>=1.8.0
    magenta 0.3.13 depends on tensorflow>=1.8.0
    magenta 0.3.12 depends on tensorflow>=1.8.0
    magenta 0.3.10 depends on tensorflow>=1.8.0
    magenta 0.3.9 depends on tensorflow>=1.8.0
    magenta 0.3.8 depends on tensorflow>=1.4.0
    magenta 0.3.7 depends on tensorflow>=1.4.0
    magenta 0.3.6 depends on tensorflow>=1.4.0
    magenta 0.3.5 depends on tensorflow>=1.4.0
    magenta 0.3.4 depends on tensorflow>=1.4.0
    magenta 0.3.3 depends on tensorflow>=1.4.0
    magenta 0.3.2 depends on tensorflow>=1.1.0
    magenta 0.3.1 depends on tensorflow>=1.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by adarob** [comment]
We already don't require a specific tensorflow version in the latest package.

**Comment by Alec-Wright** [comment]
Hi, I have the same issue when trying to install the DDSP package. Does anyone have a work around?
