### ISSUE TITLE
Listen to Transformer and Drum bot web demos not working

### ISSUE THREAD

**Issue by vumaasha** [magenta/magenta#1871]
https://magenta.github.io/listen-to-transformer/#a1_40926.mid
https://drumbot.glitch.me/

both the links are not working. There are errors on inspecting the console. Tried in chrome and firefox

**Comment by notwaldorf** [comment]
Oh no! Thanks for flagging this, I’ll take a look tomorrow!

**Comment by notwaldorf** [comment]
Fixed! For posterity, the problem was that Tone.js had a breaking change which we reflected in the latest magenta.js version (which gets loaded), but the demos were still loading the old Tone.js versions, pre-breaking change.
