### ISSUE TITLE
Onset and Frame Inference

### ISSUE THREAD

**Issue by jhlusko** [magenta/magenta#1873]
I was able to train a model on a custom dataset and use that model for transcription, hooray!

When it's training I'd like to run an eval job, but this results in the error:

File "/home/jamie/miniconda3/envs/magenta/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Feature: length (data type: int64) is required but could not be found.
	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
	 [[IteratorGetNext]]
  (1) Invalid argument: Feature: length (data type: int64) is required but could not be found.
	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
	 [[IteratorGetNext]]
	 [[PyFuncStateless/_720]]

I get the same error if I use the TFRecords and checkpoint from magenta:
TFRecords: https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/onsets_frames_dataset_maestro_v1.0.0.zip
Checkpoint:
https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/maestro_checkpoint.zip

Any advice?

**Comment by nkjulia** [comment]
hey   i am getting this error...any solutions?thx

**Comment by jhlusko** [comment]
I switched to using the pytorch version: https://github.com/jongwook/onsets-and-frames

**Comment by nkjulia** [comment]
> I switched to using the pytorch version: https://github.com/greenbech/onsets-and-frames

thanks~
