### ISSUE TITLE
Help reproducing Onsets and Frames drum transcription results

### ISSUE THREAD

**Issue by chrisdonahue** [magenta/magenta#1876]
Hi Magenta folks,

I just stumbled upon your [recent work](https://arxiv.org/pdf/2004.00188.pdf) extending O&F to drum transcription. It looks like awesome work and the example transcriptions are really compelling! I _absolutely_ agree that listening tests should always be the bottom line for evaluating transcription systems :+1: 

I was excited to reproduce the examples from the listening test as a first step towards incorporating the model into my work, but so far I've been unable to do so. Any help would be very much appreciated!

I've been using the [official O&F notebook](https://colab.research.google.com/notebooks/magenta/onsets_frames_transcription/onsets_frames_transcription.ipynb) and attempting to transcribe [Example 1 from the online supplement](https://storage.googleapis.com/magentadata/papers/e-gmd/index.html).

- [Input (original MP3)](https://storage.googleapis.com/magentadata/papers/e-gmd/listening-test/chorus-193_original.mp3)
- [Input (converted to WAV for compatibility with the Colab notebook)](https://drive.google.com/file/d/1UmduMXP-rvsNIR2hgxiTmHzbclT9VSUV/view?usp=sharing)
- [Expected output (audio)](https://storage.googleapis.com/magentadata/papers/e-gmd/listening-test/chorus-193_eg8.mp3)
- [Actual output (audio)](https://drive.google.com/file/d/1Q0J_CbiDX6udjWfmB4Q5N4s9KAj6yEwY/view?usp=sharing)
- [Actual output (MIDI)](https://drive.google.com/file/d/1PnW5MnoBK4846L9vH7ACm_ZaAbrsuvyF/view?usp=sharing)

Is it possible the listening test is using a different checkpoint from the released model? It occurred to me that the listening test may be using the 3-hit model instead of the 7-hit model used in the notebook, but the listening test audio ("Expected output" above) has hits besides kick/snare/hat.

Cheers,
Chris

**Comment by cghawthorne** [comment]
Hmm, I think there might be something wrong with the colab notebook. Can you try installing the pip package and doing inference on the command line? I'm currently getting better results that way, though I'm not sure why yet. I'll try to dig into that more soon.

Sorry for the confusion!

**Comment by cghawthorne** [comment]
Ah, I think the problem is I forgot to pass `sample_rate=hparams.sample_rate` to `audio_label_data_utils.process_record`, which is already done in the transcribe script. Without that, it will default to 16 KHz instead of the desired 44.1 KHz. Can you try adding that and see if it helps?

Also, the fact that this makes as much of a difference as it does probably means we should be doing additional training on downsampled or otherwise corrupted/augmented audio. We found that training in 44.1 KHz does help with higher frequency content like cymbal crashes, but I suspect the model could be made more robust to handling lower sample rates.

**Comment by chrisdonahue** [comment]
Thanks so much for looking into this! I really appreciate it :pray: 

Ah, a lower sample rate would explain why the hi-hats had mysteriously disappeared :). I'm not sure how to make this change in the Colab notebook, but I was able to run the command line tool (`Dockerfile` below for reference)

Unfortunately, the results ([wav](https://drive.google.com/file/d/10O0aUZ-nK6XACBogqOhM0qAQTNJ3yUfa/view?usp=sharing), [midi](https://drive.google.com/file/d/12Pbx4ukxfgwI5zD7mbjtK8CHIpa4b289/view?usp=sharing)) are still not quite as rich as the reference transcription from the online supplement. In particular, the reference really nails the syncopation of the cymbals compared to the results I'm hearing. A visual comparison (from top to bottom is original, reference, colab output, command line output):

![2021-01-05_21-38](https://user-images.githubusercontent.com/748399/103733348-6d2c9f00-4f9e-11eb-9e11-32f07d84c979.png)

One possibility I can think of is that the original file (`chorus-193_original.mp3`) was uncompressed and/or uncropped when originally fed to the network to produce the reference. Do you happen to have the original uncompressed/full-length audio file so I could test that hypothesis?

**`Dockerfile`** using the [suggested checkpoint in the README](https://github.com/magenta/magenta/tree/master/magenta/models/onsets_frames_transcription#onsets-and-frames-transcription)

```
FROM tensorflow/tensorflow:1.15.4-gpu

RUN apt-get -y update; apt-get -y install \
  wget
RUN pip install --upgrade pip

RUN apt-get -y install \
  libasound2-dev \
  libjack-dev \
  libsndfile1 \
  libsndfile-dev \
  ffmpeg

WORKDIR /models
RUN wget https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/e-gmd_checkpoint.zip
RUN ls
RUN unzip e-gmd_checkpoint.zip -d /models/e-gmd

WORKDIR /code
RUN wget https://github.com/magenta/magenta/archive/94529798dfbbb14c27ddfd76f23027dc8e2ce185.zip
RUN unzip 94529798dfbbb14c27ddfd76f23027dc8e2ce185.zip
RUN pip install --no-cache-dir -e magenta-94529798dfbbb14c27ddfd76f23027dc8e2ce185/

RUN wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1UmduMXP-rvsNIR2hgxiTmHzbclT9VSUV' -O input.wav
RUN onsets_frames_transcription_transcribe \
  --model_dir="/models/e-gmd" \
  --config="drums" \
  input.wav
```

**Comment by cghawthorne** [comment]
Yeah, given that the samplerate made such a big difference, I definitely suspect the mp3 compression could be causing problems as well. Here's the original .wav file. Note that you'll need to have `--load_audio_with_librosa=True` on the command line because the original file is a 24-bit wav.

[Chorus03_Crispy_95bpm.wav.zip](https://github.com/magenta/magenta/files/5774206/Chorus03_Crispy_95bpm.wav.zip)

**Comment by chrisdonahue** [comment]
Oh nice! I ran this and sonified the [resultant MIDI](https://drive.google.com/file/d/1o5iYR0iAZzhKqSLXSRjalvemZqkq2b3h/view?usp=sharing) with the soundfont from the paper and it sounds almost identical to the reference. Thanks so much for your help with this! Hugely appreciated

Final `Dockerfile` for posterity:

```
FROM tensorflow/tensorflow:1.15.4-gpu

RUN apt-get -y update; apt-get -y install \
  wget
RUN pip install --upgrade pip

RUN apt-get -y install \
  libasound2-dev \
  libjack-dev \
  libsndfile1 \
  libsndfile-dev \
  ffmpeg

WORKDIR /models
RUN wget https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/e-gmd_checkpoint.zip
RUN ls
RUN unzip e-gmd_checkpoint.zip -d /models/e-gmd

WORKDIR /code
RUN wget https://github.com/magenta/magenta/archive/94529798dfbbb14c27ddfd76f23027dc8e2ce185.zip
RUN unzip 94529798dfbbb14c27ddfd76f23027dc8e2ce185.zip
RUN pip install --no-cache-dir -e magenta-94529798dfbbb14c27ddfd76f23027dc8e2ce185/

RUN wget https://github.com/magenta/magenta/files/5774206/Chorus03_Crispy_95bpm.wav.zip
RUN unzip Chorus03_Crispy_95bpm.wav.zip
RUN onsets_frames_transcription_transcribe \
  --model_dir="/models/e-gmd" \
  --config="drums" \
  --load_audio_with_librosa=True \
  Chorus03_Crispy_95bpm.wav
```

**Comment by cghawthorne** [comment]
Great! The colab should be updated with the samplerate fix in the next couple days.
