### ISSUE TITLE
Onsets and Frames colab file not working

### ISSUE THREAD

**Issue by sharp-trickster** [magenta/magenta#1896]
I tried to run the first step: "Setup Environment" and it asks for different versions of packages that are incompatible amongst themselves.
it requires numba>=0.51.2 and numba==0.48.0
it requires  tensorflow-probability==0.8 and requirement tensorflow-probability==0.7.0

```
ERROR: pynndescent 0.5.2 has requirement numba>=0.51.2, but you'll have numba 0.49.1 which is incompatible.
ERROR: kfac 0.2.3 has requirement tensorflow-probability==0.8, but you'll have tensorflow-probability 0.12.1 which is incompatible.
ERROR: tensor2tensor 1.15.7 has requirement tensorflow-probability==0.7.0, but you'll have tensorflow-probability 0.12.1 which is incompatible.
ERROR: note-seq 0.0.2 has requirement numba==0.48.0, but you'll have numba 0.49.1 which is incompatible.
```

I don´t know how to fix it, because I´m still new to python and managing dependencies, so I ask you kindly to fix it.
Thank you.

**Comment by cghawthorne** [comment]
Hi @sharp-trickster. I agree the error is annoying, and I'll see if I can change some of the package requirements to get rid of at least one of those.

However, I think the colab should continue to work. If you scroll down, are you able to upload a file for inference?

**Comment by cghawthorne** [comment]
The error caused by note-seq should be gone now (https://github.com/magenta/note-seq/pull/31). I think the others are caused by some tensor2tensor-specific requirements issues. In any case, the colab should still work if you just ignore those errors.

**Comment by sharp-trickster** [comment]
Thank you, it works!
