### ISSUE TITLE
Training Onsets Frames Transcription to recognize pitch-bend?

### ISSUE THREAD

**Issue by exosome12** [magenta/magenta#1902]
Hello,

Can the onset frames transcription set in a way that pitch-bend is taken to account during training and prediction?

**Comment by cghawthorne** [comment]
We don't currently have any code that handles pitch bends for transcription. It would be an interesting thing to try, though. Part of the difficulty would be getting a dataset with an accurate pairing of audio and pitch bend events. From there, I could imagine modeling the bends either as a series of discrete notes (probably easiest) or as additional bend or F0 contour events.

If you try it out, I'd love to hear how it goes!
