### ISSUE TITLE
Onset&Frames real-time prediction on mobile device

### ISSUE THREAD

**Issue by tranctan** [magenta/magenta#1907]
Hi, I currently need to have a Piano Transcription model on mobile devices (runs real-time). Is there any work on bringing Onset&Frames model to predict real-time on a mobile device? Any suggestions or discussions are greatly welcome.

**Comment by cghawthorne** [comment]
We have some demos of realtime transcription using TFLite here: https://github.com/magenta/magenta/tree/master/magenta/models/onsets_frames_transcription/realtime

Unfortunately, we haven't had time to develop them beyond the initial experimental demo. Let us know if you end up doing something interesting with them!
