### ISSUE TITLE
training stuck 

### ISSUE THREAD

**Issue by omkarprissoft** [magenta/magenta#1908]
I used basic_rnn to training model but it stucks and show "I0406 13:32:59.821563 12440 basic_session_run_hooks.py:625] Calling checkpoint listeners after saving checkpoint 0..."

**Comment by where-is-brett** [comment]
Same here when running in colab. Any idea what is causing this? I am inclined to think it is a TF version compatibility issue.

**Comment by omkarprissoft** [comment]
no idea , Not working on it .

**Comment by sameedhayat** [comment]
Hi,
I am getting the same issue, was anyone able to resolve it. Thanks.
