### ISSUE TITLE
Can we use MAESTRO Dataset for training AI in commercial app ? 

### ISSUE THREAD

**Issue by namtm84** [magenta/magenta#1915]
Dear Magenta team

We make a commercial mobile app, and we want to use  MAESTRO Dataset for training our model. How can we get the license for that purpose?

Thank you

**Comment by cghawthorne** [comment]
Hi @namtm84. You should try reaching out to piano-e-competition.com. They were the source of the raw data we used when creating the dataset and distributing MAESTRO under a noncommercial license is a part of our agreement with them, so they would be the right people to talk to about getting a commercial license for it.

Best of luck on the app, and keep us posted on how it goes!
