### ISSUE TITLE
A question run drum config in onset and frames model on GPU

### ISSUE THREAD

**Issue by chris666-sys** [magenta/magenta#1925]
Hello,

I am not good at English, Hope to hear from you, very grateful...

I am trying to train drums model on GPU (not TPU) using E-GMD dataset (run drum config in onset and frames model on GPU).

1. First I used (onsets_frames_transcription_create_tfrecords script) to get (train.tfrecord-00000-of-00001 file), and then started to use the official method of github (TPUonsets_frames_transcription_train script) to try training...

2.I set ('config', ‘drums’,’use_tpu’, False) in the (onsets_frames_transcription_train.py) file

3. I changed some settings of the estimator_spec_util.py file, because if it is not changed, there will be an error
   optimizer=‘Adam’,
   tf.tpu.estimator.TPUEstimatorSpec -> tf.estimator.EstimatorSpec

4. But got this errors:

**tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: assertion failed: [Condition x <= y did not hold element-wise:] [x (wav_to_num_frames_op:0) = ] [178] [y (assert_less_equal
/y:0) = ] [100]
         [[{{node assert_less_equal/Assert/Assert}}]]
         [[IteratorGetNext]]
  (1) Invalid argument: assertion failed: [Condition x <= y did not hold element-wise:] [x (wav_to_num_frames_op:0) = ] [178] [y (assert_less_equal
/y:0) = ] [100]
         [[{{node assert_less_equal/Assert/Assert}}]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_1047]]**

5.Thank you very much for your reply！

**Comment by cghawthorne** [comment]
I think the issue is that after running `onsets_frames_transcription_create_tfrecords`, you still need to run `onsets_frames_transcription_create_dataset` with the relevant flags to process the data for training.

The error that you're seeing indicates that the data is longer than expected for training: https://github.com/magenta/magenta/blob/master/magenta/models/onsets_frames_transcription/data.py#L375 The create_dataset script will take care of splitting full length examples into shorter sequences for training.

**Comment by hejiangmyai** [comment]
Hi @cghawthorne 

Thank you very much for your reply and guidance...

Following your guide, I am using <onsets_frames_transcription_create_dataset> to process <train.tfrecord-00000-of-00001> data. According to the official method as follows:

```
BUCKET=magenta_storage
PROJECT=total-now-314808
MAGENTA_SETUP_PATH=/path/to/magenta/setup.py

PIPELINE_OPTIONS=\
"--region=us-central1-c,"
"--runner=DataflowRunner,"\
"--project=${PROJECT},"\
"--temp_location=gs://${BUCKET}/tmp,"\
"--setup_file=${MAGENTA_SETUP_PATH}"

onsets_frames_transcription_create_dataset \
  --output_directory=gs://${BUCKET}/examples \
  --pipeline_options="${PIPELINE_OPTIONS}" \
  —Alsologtostderr
```

At the same time, I modified the DATASET_CONFIG_MAP->DatasetConfig->gs://...settings in the configs.py file
Set the relevant tf-data path of ‘drums’...
After executing the above <onsets_frames_transcription_create_dataset>, my command line terminal prints like this, as follows:


`I0605 10:57:50.298470 140104330516288 fn_runner.py:521] Running ((((((read_tfrecord_train/ReadAllFiles/Reshard/ReshufflePerKey/GroupByKey/Read)+(ref_AppliedPTransform_read_tfrecord_train/ReadAllFiles/Reshard/Restore_Key/time (ref_AppliedPTransform_read_tfrecord_train / ReadAllFiles / Reshard / RemoveRandomKeys_16)) + (ref_AppliedPTransform_read_tfrecord_train / ReadAllFiles / ReadRange_17)) + (ref_AppliedPTransform_shuffle_input_train / AddRandomKeys_19)) + (ref_AppliedPTransform_shuffle_input_train / ReshufflePerKey / Map (reify_timestamps) _21)) + (shuffle_input_train / ReshufflePerKey / GroupByKey / Write)`


Now my command line terminal has no more log information printed out. The above information has been displayed for  an hour. I am not sure if this is correct? Do I need to wait like this until the whole process is processed?

Thank you again for your reply and guidance!

**Comment by chris666-sys** [comment]
@cghawthorne Thank you for your reply and guidance, thank you very much！

**Comment by chris666-sys** [comment]
Hello @cghawthorne, Thank you for your last reply

I am using E-GMD data to train drums model, <onset and frames>

I ran the `onsets_frames_transcription_create_dataset` script according to your instructions, and used Dataflow to  got the processed data, like this: `train.tfrecord-00000-of-00126` There are 126 such files, about 30G

Then I put the 126 train.tfrecord files in the specified directory: `./chris/examples/train`, and then started to run the `onsets_frames_transcription_train` script as follows:

```
TRAIN_EXAMPLES=./chris/examples/train
RUN_DIR=./chris/modle

onsets_frames_transcription_train \
  --examples_path="${TRAIN_EXAMPLES}" \
  --model_dir="${RUN_DIR}" \
  --config='drums' \
  --use_tpu=False \
  --mode='train'
```

But got the following error:

```
NFO:tensorflow:training_loop marked as finished
I0606 05:57:46.054360 140684865611584 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0606 05:57:46.054666 140684865611584 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/home/chris/miniconda3/envs/magenta_deve/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/chris/miniconda3/envs/magenta_deve/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/chris/miniconda3/envs/magenta_deve/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1451, in _call_tf
_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: chris/examples/train; Is a directory
         [[{{node IteratorGetNext}}]]
  (1) Failed precondition: chris/examples/train; Is a directory
         [[{{node IteratorGetNext}}]]
         [[IteratorGetNext/_1049]]
0 successful operations.
0 derived errors ignored.
```

Then I changed `TRAIN_EXAMPLES=./chris/examples/train`  to `TRAIN_EXAMPLES=./chris/examples/train/train.*` to get the tfrecord file, but this error occurred:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument: assertion failed: [Condition x <= y did not hold element-wise:] [x (wav_to_num_frames_op:0) = ] [178] [y (assert_less_equal
/y:0) = ] [100]
[[{{node assert_less_equal/Assert/Assert}}]]
[[IteratorGetNext]]
(1) Invalid argument: assertion failed: [Condition x <= y did not hold element-wise:] [x (wav_to_num_frames_op:0) = ] [178] [y (assert_less_equal
/y:0) = ] [100]
[[{{node assert_less_equal/Assert/Assert}}]]
[[IteratorGetNext]]
[[IteratorGetNext/_1047]]
```

May I ask what is the problem? Thank you very much for your reply and guidance
