### ISSUE TITLE
A Question About drum model training using E-GMD data

### ISSUE THREAD

**Issue by chris666-sys** [magenta/magenta#1931]
**Dear magenta team:**

I am using `E-GMD` data to train `drums` model <onsets_frames>

I used the `onsets_frames_transcription_train` script to train the **drums model**. I have been training for `2` days. Currently, I have trained to `4200` steps and generated `checkpoint` and `model.ckpt-4200.data-00000-of-00001`,`model.ckpt-4200.index`,`model.ckpt- 4200.meta `and so on, these files, and then I used the `onsets_frames_transcription_transcribe` script to convert the `wav` file to a `midi` file, but unfortunately the midi file I got was only `56B` in size, and then I opened the midi file with `MuseScore` and found that there was nothing in the file , Not a single note. As shown below:

![modlepic](https://user-images.githubusercontent.com/19420482/121654257-1f2d4180-cad0-11eb-8372-c8002cab109a.png)
<img width="988" alt="nothing@2x" src="https://user-images.githubusercontent.com/19420482/121654291-27857c80-cad0-11eb-9c5f-a3ca4a942caa.png">
**The Training Loss**
![333](https://user-images.githubusercontent.com/19420482/121673429-725cbf80-cae3-11eb-9ba1-304264290496.png)
**-------------------------------------------------------------------------------------------------------------------------**
Then I used magenta's official `checkpoint` file to convert the above wav to a midi file. The midi file size is `465B`. After opening it with `MuseScore`, I can see the converted notes and play them. As shown below:

![note_model](https://user-images.githubusercontent.com/19420482/121655066-e9d52380-cad0-11eb-9fab-4fce0d077609.png)

<img width="1002" alt="note@2x" src="https://user-images.githubusercontent.com/19420482/121654326-31a77b00-cad0-11eb-8558-32435b4a9591.png">

**My Question:**

1. I saw that the official training step number is `569,400`. I currently train to `4200` steps. I want to test how the model I trained performs, but I found that there is no note in the midi file. Is it because the number of steps I trained is too few? ? Or is there a problem with the model? According to my understanding, a small number of training steps will cause the model to be inaccurate and the notes will be wrong, but it should not lead to no notes in the midi file. So, what is the problem?

2. It took `two days` to train to `4200` steps (Google VM GPU: NVIDIA Tesla K80). If I want to train to `569,400` steps, it takes `270` days according to the current computing power. This time seems too long, but I I don't know where is the problem. Below is the data (`about 30G size use E-GMD` )used for training...
<img width="1178" alt="train_data" src="https://user-images.githubusercontent.com/19420482/121658808-4259f000-cad4-11eb-810b-936eded52796.png">

**Thank you very much again, and hope to get your reply!**

-----------------------------------------------------------------------------------------------------------------------

**The following is the log information when running onsets_frames_transcription_transcribe with the model I trained`**

I0611 07:20:08.749365 139783536817984 tpu_context.py:271] _TPUContext: eval_on_tpu False
2021-06-11 07:20:08.757312: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neura
l Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-11 07:20:08.757992: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:08.758846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: NVIDIA Tesla K80 computeCapability: 3.7
coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s
2021-06-11 07:20:08.758973: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:08.759819: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:08.760558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-06-11 07:20:08.761777: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.s
o.11.0
2021-06-11 07:20:10.176148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edg
e matrix:
2021-06-11 07:20:10.176217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-06-11 07:20:10.176245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-06-11 07:20:10.176558: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:10.177446: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:10.178291: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:10.179112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/ta
sk:0/device:GPU:0 with 10800 MB memory) -> physical GPU (device: 0, name: NVIDIA Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3
.7)
2021-06-11 07:20:10.238793: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2299995000 Hz
INFO:tensorflow:Starting transcription for 1623159913088803.wav...
I0611 07:20:10.322484 139783536817984 onsets_frames_transcription_transcribe.py:112] Starting transcription for 1623159913088803.wav...
INFO:tensorflow:Processing file...
I0611 07:20:10.322793 139783536817984 onsets_frames_transcription_transcribe.py:118] Processing file...
/home/chris666/miniconda3/envs/magenta_deve/lib/python3.8/site-packages/note_seq/audio_io.py:117: WavFileWarning: Chunk (non-data) not
 understood, skipping it.
  native_sr, y = scipy.io.wavfile.read(io.BytesIO(wav_data))
2021-06-11 07:20:12.297830: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enable
d (registered 2)
2021-06-11 07:20:12.978430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: NVIDIA Tesla K80 computeCapability: 3.7
coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s
2021-06-11 07:20:12.979045: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:12.980476: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:12.981795: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-06-11 07:20:12.982012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edg
e matrix:
2021-06-11 07:20:12.982165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-06-11 07:20:12.982295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-06-11 07:20:12.982681: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:12.984172: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:12.985464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/ta
sk:0/device:GPU:0 with 10800 MB memory) -> physical GPU (device: 0, name: NVIDIA Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3
.7)
INFO:tensorflow:Calling model_fn.
I0611 07:20:13.126230 139783536817984 estimator.py:1162] Calling model_fn.
INFO:tensorflow:Running infer on CPU/GPU
I0611 07:20:13.126519 139783536817984 tpu_estimator.py:3198] Running infer on CPU/GPU
/home/chris666/miniconda3/envs/magenta_deve/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarn
ing: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
/home/chris666/miniconda3/envs/magenta_deve/lib/python3.8/site-packages/tensorflow/python/keras/layers/legacy_rnn/rnn_cell_impl.py:708
: UserWarning: `tf.nn.rnn_cell.BasicLSTMCell` is deprecated and will be removed in a future version. This class is equivalent as `tf.keras.
layers.LSTMCell`, and will be replaced by that in Tensorflow 2.0.
  warnings.warn("`tf.nn.rnn_cell.BasicLSTMCell` is deprecated and will be "
WARNING:tensorflow:From /home/chris666/magenta/magenta/contrib/rnn.py:464: bidirectional_dynamic_rnn (from tensorflow.python.ops.rnn) 
is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
W0611 07:20:13.276268 139783536817984 deprecation.py:330] From /home/chris666/magenta/magenta/contrib/rnn.py:464: bidirectional_dynami
c_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
WARNING:tensorflow:From /home/chris666/miniconda3/envs/magenta_deve/lib/python3.8/site-packages/tensorflow/python/ops/rnn.py:438: dyna
mic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W0611 07:20:13.276689 139783536817984 deprecation.py:330] From /home/chris666/miniconda3/envs/magenta_deve/lib/python3.8/site-packages
/tensorflow/python/ops/rnn.py:438: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
/home/chris666/miniconda3/envs/magenta_deve/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1700: UserWarn
ing: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '
WARNING:tensorflow:From /home/chris666/miniconda3/envs/magenta_deve/lib/python3.8/site-packages/tensorflow/python/keras/layers/legacy_
rnn/rnn_cell_impl.py:759: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a fu
ture version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0611 07:20:13.329888 139783536817984 deprecation.py:528] From /home/chris666/miniconda3/envs/magenta_deve/lib/python3.8/site-packages
/tensorflow/python/keras/layers/legacy_rnn/rnn_cell_impl.py:759: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is
 deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /home/chris666/magenta/magenta/models/onsets_frames_transcription/metrics.py:74: to_float (from tensorflow.pyt
hon.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0611 07:20:14.325912 139783536817984 deprecation.py:330] From /home/chris666/magenta/magenta/models/onsets_frames_transcription/metri
cs.py:74: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From /home/chris666/magenta/magenta/models/onsets_frames_transcription/metrics.py:90: div (from tensorflow.python.o
ps.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
W0611 07:20:14.345736 139783536817984 deprecation.py:330] From /home/chris666/magenta/magenta/models/onsets_frames_transcription/metri
cs.py:90: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
INFO:tensorflow:Done calling model_fn.
I0611 07:20:15.771646 139783536817984 estimator.py:1164] Done calling model_fn.
INFO:tensorflow:Graph was finalized.
I0611 07:20:15.959807 139783536817984 monitored_session.py:247] Graph was finalized.
2021-06-11 07:20:15.960485: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:15.961305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: NVIDIA Tesla K80 computeCapability: 3.7
coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s
2021-06-11 07:20:15.961431: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:15.962248: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:15.962997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-06-11 07:20:15.963047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edg
e matrix:
2021-06-11 07:20:15.963069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-06-11 07:20:15.963102: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-06-11 07:20:15.963240: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:15.964063: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative v
alue (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-11 07:20:15.964803: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/ta
sk:0/device:GPU:0 with 10800 MB memory) -> physical GPU (device: 0, name: NVIDIA Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3
.7)
INFO:tensorflow:Restoring parameters from ./transcription_script/drums/checkpoint_eval/model.ckpt-4200
I0611 07:20:15.964960 139783536817984 saver.py:1298] Restoring parameters from ./transcription_script/drums/checkpoint_eval/model.ckpt-4200
INFO:tensorflow:Running local_init_op.
I0611 07:20:16.424001 139783536817984 session_manager.py:531] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0611 07:20:16.444065 139783536817984 session_manager.py:534] Done running local_init_op.
2021-06-11 07:20:17.650932: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so
.8
2021-06-11 07:20:18.672658: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8100
2021-06-11 07:20:20.394429: E tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directo
ry
2021-06-11 07:20:20.394485: W tensorflow/stream_executor/gpu/asm_compiler.cc:56] Couldn't invoke ptxas --version
2021-06-11 07:20:20.395000: E tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directo
ry
2021-06-11 07:20:20.395080: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Failed to launch ptxas
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
2021-06-11 07:20:20.475173: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.s
o.11
2021-06-11 07:20:21.764202: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt
.so.11
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavHHClosed_Bow' with length 1378
I0611 07:20:24.570418 139778786342656 metrics.py:130] Calculating metrics for b'1623159913088803.wavHHClosed_Bow' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavTom3_Head' with length 1378
I0611 07:20:24.571233 139778435577600 metrics.py:130] Calculating metrics for b'1623159913088803.wavTom3_Head' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavHHClosed_Edge' with length 1378
I0611 07:20:24.572410 139778803128064 metrics.py:130] Calculating metrics for b'1623159913088803.wavHHClosed_Edge' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavTom3_Rim' with length 1378
I0611 07:20:24.573850 139778811520768 metrics.py:130] Calculating metrics for b'1623159913088803.wavTom3_Rim' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavHHOpen_Edge' with length 1378
I0611 07:20:24.575503 139778819913472 metrics.py:130] Calculating metrics for b'1623159913088803.wavHHOpen_Edge' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavHHOpen_Bow' with length 1378
I0611 07:20:24.577293 139778836698880 metrics.py:130] Calculating metrics for b'1623159913088803.wavHHOpen_Bow' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavTom1' with length 1378
I0611 07:20:24.578152 139778794735360 metrics.py:130] Calculating metrics for b'1623159913088803.wavTom1' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavHHPedal' with length 1378
I0611 07:20:24.580187 139778828306176 metrics.py:130] Calculating metrics for b'1623159913088803.wavHHPedal' with length 1378
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavHHClosed_Bow':
I0611 07:20:24.583262 139778786342656 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavHH
Closed_Bow':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavHHOpen_Edge':
I0611 07:20:24.584774 139778819913472 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavHH
Open_Edge':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavHHOpen_Bow':
I0611 07:20:24.585694 139778836698880 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavHH
Open_Bow':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTom3_Head':
I0611 07:20:24.585992 139778435577600 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTo
m3_Head':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavHHClosed_Edge':
I0611 07:20:24.587209 139778803128064 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavHH
Closed_Edge':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTom3_Rim':
I0611 07:20:24.587305 139778811520768 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTo
m3_Rim':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTom1':
I0611 07:20:24.587461 139778794735360 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTo
m1':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavHHPedal':
I0611 07:20:24.589186 139778828306176 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavHH
Pedal':
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavSnare_Head' with length 1378
I0611 07:20:24.600442 139778811520768 metrics.py:130] Calculating metrics for b'1623159913088803.wavSnare_Head' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavCrash2_Edge' with length 1378
I0611 07:20:24.601109 139778836698880 metrics.py:130] Calculating metrics for b'1623159913088803.wavCrash2_Edge' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavKick' with length 1378
I0611 07:20:24.601798 139778803128064 metrics.py:130] Calculating metrics for b'1623159913088803.wavKick' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavCrash2_Bow' with length 1378
I0611 07:20:24.602365 139778819913472 metrics.py:130] Calculating metrics for b'1623159913088803.wavCrash2_Bow' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavCrash1_Edge' with length 1378
I0611 07:20:24.603837 139778828306176 metrics.py:130] Calculating metrics for b'1623159913088803.wavCrash1_Edge' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavCrash1_Bow' with length 1378
I0611 07:20:24.604430 139778786342656 metrics.py:130] Calculating metrics for b'1623159913088803.wavCrash1_Bow' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavTom2_Rim' with length 1378
I0611 07:20:24.605441 139778794735360 metrics.py:130] Calculating metrics for b'1623159913088803.wavTom2_Rim' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavRide_Bow' with length 1378
I0611 07:20:24.606982 139778435577600 metrics.py:130] Calculating metrics for b'1623159913088803.wavRide_Bow' with length 1378
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCrash2_Edge':
I0611 07:20:24.609383 139778836698880 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCr
ash2_Edge':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCrash2_Bow':
I0611 07:20:24.609704 139778819913472 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCr
ash2_Bow':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTom2_Rim':
I0611 07:20:24.610153 139778794735360 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTo
m2_Rim':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCrash1_Bow':
I0611 07:20:24.610687 139778786342656 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCr
ash1_Bow':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavKick':
I0611 07:20:24.610777 139778803128064 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavKi
ck':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavRide_Bow':
I0611 07:20:24.611132 139778435577600 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavRi
de_Bow':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCrash1_Edge':
I0611 07:20:24.611603 139778828306176 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCr
ash1_Edge':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavSnare_Head':
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavTom2' with length 1378
I0611 07:20:24.614379 139778811520768 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavSn
are_Head':
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavRide_Edge' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavClaves' with length 1378
I0611 07:20:24.615391 139778794735360 metrics.py:130] Calculating metrics for b'1623159913088803.wavTom2' with length 1378
I0611 07:20:24.616217 139778836698880 metrics.py:130] Calculating metrics for b'1623159913088803.wavRide_Edge' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavRide_Bell' with length 1378
I0611 07:20:24.616937 139778819913472 metrics.py:130] Calculating metrics for b'1623159913088803.wavClaves' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavClap' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavClap' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavTambourine' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavCowbell' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavMaracas' with length 1378
I0611 07:20:24.617849 139778786342656 metrics.py:130] Calculating metrics for b'1623159913088803.wavRide_Bell' with length 1378
I0611 07:20:24.618323 139778803128064 metrics.py:130] Calculating metrics for b'1623159913088803.wavClap' with length 1378
I0611 07:20:24.619403 139778435577600 metrics.py:130] Calculating metrics for b'1623159913088803.wavTambourine' with length 1378
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavRide_Edge':
I0611 07:20:24.621160 139778828306176 metrics.py:130] Calculating metrics for b'1623159913088803.wavCowbell' with length 1378
I0611 07:20:24.621927 139778811520768 metrics.py:130] Calculating metrics for b'1623159913088803.wavMaracas' with length 1378
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavClaves':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTom2':
I0611 07:20:24.622907 139778836698880 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavRi
de_Edge':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavRide_Bell':
I0611 07:20:24.623837 139778819913472 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCl
aves':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTambourine':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavClap':
I0611 07:20:24.623937 139778794735360 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTo
m2':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCowbell':
I0611 07:20:24.625653 139778786342656 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavRi
de_Bell':
I0611 07:20:24.626234 139778435577600 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTa
mbourine':
I0611 07:20:24.626361 139778803128064 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCl
ap':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavMaracas':
I0611 07:20:24.627326 139778828306176 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavCo
wbell':
I0611 07:20:24.627664 139778811520768 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavMa
racas':
INFO:tensorflow:Calculating metrics for b'1623159913088803.wav' with length 1378
I0611 07:20:24.629846 139778836698880 metrics.py:130] Calculating metrics for b'1623159913088803.wav' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavTom1_Rim' with length 1378
I0611 07:20:24.631598 139778794735360 metrics.py:130] Calculating metrics for b'1623159913088803.wavTom1_Rim' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavSnare_Rim' with length 1378
I0611 07:20:24.632023 139778819913472 metrics.py:130] Calculating metrics for b'1623159913088803.wavSnare_Rim' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavSnare_X-Stick' with length 1378
I0611 07:20:24.634879 139778828306176 metrics.py:130] Calculating metrics for b'1623159913088803.wavSnare_X-Stick' with length 1378
INFO:tensorflow:Calculating metrics for b'1623159913088803.wavLow_Conga' with length 1378
I0611 07:20:24.635435 139778435577600 metrics.py:130] Calculating metrics for b'1623159913088803.wavLow_Conga' with length 1378
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wav':
I0611 07:20:24.636327 139778836698880 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wav':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTom1_Rim':
I0611 07:20:24.636675 139778794735360 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavTo
m1_Rim':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavSnare_Rim':
I0611 07:20:24.637044 139778819913472 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavSn
are_Rim':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavSnare_X-Stick':
I0611 07:20:24.639137 139778828306176 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavSn
are_X-Stick':
INFO:tensorflow:Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavLow_Conga':
I0611 07:20:24.640116 139778435577600 metrics.py:184] Reference pitches were length 0, returning empty metrics for b'1623159913088803.wavLo
w_Conga':
INFO:tensorflow:prediction_loop marked as finished
I0611 07:20:24.717015 139783536817984 error_handling.py:115] prediction_loop marked as finished
INFO:tensorflow:prediction_loop marked as finished
I0611 07:20:24.717265 139783536817984 error_handling.py:115] prediction_loop marked as finished
INFO:tensorflow:Transcription written to **`1623159913088803.wav.midi`**.
I0611 07:20:24.718230 139783536817984 onsets_frames_transcription_transcribe.py:146] Transcription written to 1623159913088803.wav.midi.

**Comment by cghawthorne** [comment]
Hi @chris666-sys, unfortunately this isn't entirely unexpected. In the very first few steps of the model, you're correct that it will output a lot of random garbage, with a lot of predicted notes. But quickly after that, the model learns that for any given "pitch" (kind of drum hit) and timestep combination, silence is more likely than anything else, so the model switches to predicting zero or very few notes. Only after training longer than that will you start to see note prediction results.

I don't remember offhand how many steps each of those "phases" of learning lasted, but outputting 0 notes after 4.2k steps seems in line with what I'd expect.

Unfortunately, for a model and dataset of this size, I think you'll need more accelerator resources for practical training. For the model in the paper, we used 16 TPUv3 cores over 3 days. In GPUs, that's around the same as 16 V100 GPUs. So, not only parallelizing across more GPUs than you're using, but considerably more powerful than a K80 too.

Perhaps for your use case it would work to start with our pretrained model and finetune it rather than training from scratch?

**Comment by chris666-sys** [comment]
Thank you for your reply, thank you very much!
