### ISSUE TITLE
e-GMD: Don't know which sound MIDI note No. 22 and 26 refer to.

### ISSUE THREAD

**Issue by Thanyanit-J** [magenta/magenta#1957]
After converting e-GMD MIDI files to NoteSequence, I notice that some notes are No. 22 and 26 (pitch) which I don't know what both of them refer to.
For MIDI Channel 10, I understand that note numbers are between 27 and 87. So, do you know which sound are 22 and 26 ?

**Comment by cghawthorne** [comment]
Hi @Thanyanit-J, you're right that those aren't standard MIDI notes. They come as a result of using a Roland drum kit to do the recording, which uses a non-standard set of notes to represent different hits.

You can see the full mapping in the dataset E-GMD was based on: [Groove MIDI Dataset](https://g.co/magenta/groove-dataset).

You may also find the mappings we used for our paper useful in [Table 2](https://goo.gl/magenta/e-gmd-paper) or in [drump_mappings.py](https://github.com/magenta/magenta/blob/main/magenta/models/onsets_frames_transcription/drum_mappings.py).

Let me know if you have any other questions!
