### ISSUE TITLE
Could someone tell me how many parameters onset_frame__transcription model for piano music transcription has?

### ISSUE THREAD

**Issue by wwpww** [magenta/magenta#1965]
Thank you very much for your answer

**Comment by cghawthorne** [comment]
The version from the MAESTRO paper 28M parameters. I think we forgot to mention that in the MAESTRO paper, but we do discuss it in the Sequence-to-Sequence Piano Transcription paper: https://arxiv.org/pdf/2107.09142.pdf (section 3.1)
