### ISSUE TITLE
"Generating Piano Music with Transformer" colab notebook is broken.

### ISSUE THREAD

**Issue by abrosen** [magenta/magenta#1972]
https://colab.research.google.com/notebooks/magenta/piano_transformer/piano_transformer.ipynb

Program breaks on the third code block "Setup and Load Checkpoint"

---------------------------------------------------------------------------

NotImplementedError                       Traceback (most recent call last)

[<ipython-input-5-ec5e9eba3bd7>](https://localhost:8080/#) in <module>()
     53 
     54 # "Burn" one.
---> 55 _ = next(unconditional_samples)

17 frames

[/tensorflow-1.15.2/python3.7/tensorflow_estimator/python/estimator/estimator.py](https://localhost:8080/#) in predict(self, input_fn, predict_keys, hooks, checkpoint_path, yield_single_examples)
    620             input_fn, ModeKeys.PREDICT)
    621         estimator_spec = self._call_model_fn(
--> 622             features, None, ModeKeys.PREDICT, self.config)
    623 
    624         # Call to warm_start has to be after model_fn is called.

[/tensorflow-1.15.2/python3.7/tensorflow_estimator/python/estimator/estimator.py](https://localhost:8080/#) in _call_model_fn(self, features, labels, mode, config)
   1147 
   1148     logging.info('Calling model_fn.')
-> 1149     model_fn_results = self._model_fn(features=features, **kwargs)
   1150     logging.info('Done calling model_fn.')
   1151 

[/tensorflow-1.15.2/python3.7/tensor2tensor/utils/t2t_model.py](https://localhost:8080/#) in wrapping_model_fn(features, labels, mode, params, config)
   1413           params=params,
   1414           decode_hparams=decode_hparams,
-> 1415           use_tpu=use_tpu)
   1416 
   1417     return wrapping_model_fn

[/tensorflow-1.15.2/python3.7/tensor2tensor/utils/t2t_model.py](https://localhost:8080/#) in estimator_model_fn(cls, hparams, features, labels, mode, config, params, decode_hparams, use_tpu)
   1470           shape[1] = hparams.max_input_seq_length or hparams.max_length
   1471         inputs.set_shape(shape)
-> 1472       return model.estimator_spec_predict(features, use_tpu=use_tpu)
   1473 
   1474     # TRAIN and EVAL modes

[/tensorflow-1.15.2/python3.7/tensor2tensor/utils/t2t_model.py](https://localhost:8080/#) in estimator_spec_predict(self, features, use_tpu)
   1694         alpha=decode_hparams.alpha,
   1695         decode_length=decode_hparams.extra_length,
-> 1696         use_tpu=use_tpu)
   1697     if isinstance(infer_out, dict):
   1698       outputs = infer_out["outputs"]

[/tensorflow-1.15.2/python3.7/tensor2tensor/utils/t2t_model.py](https://localhost:8080/#) in infer(self, features, decode_length, beam_size, top_beams, alpha, use_tpu)
    811       if beam_size == 1:
    812         log_info("Greedy Decoding")
--> 813         results = self._greedy_infer(features, decode_length, use_tpu)
    814       else:
    815         log_info("Beam Decoding with beam size %d" % beam_size)

[/tensorflow-1.15.2/python3.7/tensor2tensor/models/transformer.py](https://localhost:8080/#) in _greedy_infer(self, features, decode_length, use_tpu)
    340       if use_tpu:
    341         return self._fast_decode_tpu(features, decode_length)
--> 342       return self._fast_decode(features, decode_length)
    343 
    344   def _beam_decode(self,

[/tensorflow-1.15.2/python3.7/tensor2tensor/models/transformer.py](https://localhost:8080/#) in _fast_decode(self, features, decode_length, beam_size, top_beams, alpha)
    793 
    794     decoder_self_attention_bias = (
--> 795         common_attention.attention_bias_lower_triangle(decode_length))
    796     if hparams.proximity_bias:
    797       decoder_self_attention_bias += common_attention.attention_bias_proximal(

[/tensorflow-1.15.2/python3.7/tensor2tensor/utils/expert_utils.py](https://localhost:8080/#) in decorated(*args, **kwargs)
     58       name = kwargs.pop("name", None)  # Python 2 hack for keyword only args
     59       with scope_fn(name or scope or f.__name__):
---> 60         return f(*args, **kwargs)
     61 
     62     return decorated

[/tensorflow-1.15.2/python3.7/tensor2tensor/layers/common_attention.py](https://localhost:8080/#) in attention_bias_lower_triangle(length)
    913     a `Tensor` with shape [1, 1, length, length].
    914   """
--> 915   return attention_bias_local(length, -1, 0)
    916 
    917 

[/tensorflow-1.15.2/python3.7/tensor2tensor/utils/expert_utils.py](https://localhost:8080/#) in decorated(*args, **kwargs)
     58       name = kwargs.pop("name", None)  # Python 2 hack for keyword only args
     59       with scope_fn(name or scope or f.__name__):
---> 60         return f(*args, **kwargs)
     61 
     62     return decorated

[/tensorflow-1.15.2/python3.7/tensor2tensor/layers/common_attention.py](https://localhost:8080/#) in attention_bias_local(length, max_backward, max_forward)
    897       max_backward,
    898       max_forward,
--> 899       out_shape=[1, 1, length, length])
    900   return -1e9 * (1.0 - band)
    901 

[/tensorflow-1.15.2/python3.7/tensor2tensor/layers/common_layers.py](https://localhost:8080/#) in ones_matrix_band_part(rows, cols, num_lower, num_upper, out_shape)
   2998   else:
   2999     band = tf.matrix_band_part(
-> 3000         tf.ones([rows, cols]), tf.cast(num_lower, tf.int64),
   3001         tf.cast(num_upper, tf.int64))
   3002     if out_shape:

[/tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/array_ops.py](https://localhost:8080/#) in ones(shape, dtype, name)
   2558         # Create a constant if it won't be very big. Otherwise create a fill op
   2559         # to prevent serialized GraphDefs from becoming too large.
-> 2560         output = _constant_if_small(one, shape, dtype, name)
   2561         if output is not None:
   2562           return output

[/tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/array_ops.py](https://localhost:8080/#) in _constant_if_small(value, shape, dtype, name)
   2293 def _constant_if_small(value, shape, dtype, name):
   2294   try:
-> 2295     if np.prod(shape) < 1000:
   2296       return constant(value, shape=shape, dtype=dtype, name=name)
   2297   except TypeError:

<__array_function__ internals> in prod(*args, **kwargs)

[/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py](https://localhost:8080/#) in prod(a, axis, dtype, out, keepdims, initial, where)
   3050     """
   3051     return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
-> 3052                           keepdims=keepdims, initial=initial, where=where)
   3053 
   3054 

[/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py](https://localhost:8080/#) in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     84                 return reduction(axis=axis, out=out, **passkwargs)
     85 
---> 86     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     87 
     88 

[/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/ops.py](https://localhost:8080/#) in __array__(self)
    734   def __array__(self):
    735     raise NotImplementedError("Cannot convert a symbolic Tensor ({}) to a numpy"
--> 736                               " array.".format(self.name))
    737 
    738   def __len__(self):

NotImplementedError: Cannot convert a symbolic Tensor (transformer/add:0) to a numpy array.

**Comment by TimOgden** [comment]
The issue is that Colab comes with numpy version 1.21.5 by default. I'm not sure the exact issue, but has to do with the notebook only using tensorflow 1.x. Seems like it isn't until tensorflow 2.x that they allow ops to be represented as numpy arrays?

The solution is to get an earlier version of numpy.

In the first code block ("Environment Setup") I added
`!pip uninstall numpy
!pip install numpy==1.19.5`

In order for it to take effect, you need to run this code block once after connecting, then restart the runtime and run it all again.

**Comment by iansimon** [comment]
The numpy downgrade fix should work on a fresh runtime.  Just add a cell before the very first cell that looks like:

```
!pip uninstall -y numpy
!pip install numpy==1.19
```

You will then be prompted to restart the runtime, which you should.  After that, the subsequent cells should work.

**Comment by abrosen** [comment]
Unfortunately it is broken again.

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-1-79be332e03dc>](https://localhost:8080/#) in <module>
      4 #@markdown for running the Transformer models.
      5 
----> 6 get_ipython().run_line_magic('tensorflow_version', '1.x')
      7 
      8 print('Copying Salamander piano SoundFont (via https://sites.google.com/site/soundfonts4u) from GCS...')

1 frames

[/usr/local/lib/python3.7/dist-packages/google/colab/_tensorflow_magics.py](https://localhost:8080/#) in _tensorflow_version(line)
     39 
     40              Your notebook should be updated to use Tensorflow 2.
---> 41              See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2."""
     42                        ))
     43 

ValueError: Tensorflow 1 is unsupported in Colab.

Your notebook should be updated to use Tensorflow 2.
See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2.
