### ISSUE TITLE
Generating Piano Music with Transformer for colab bug

### ISSUE THREAD

**Issue by shxluo** [magenta/magenta#1988]
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-5-ec5e9eba3bd7>](https://localhost:8080/#) in <module>()
     53 
     54 # "Burn" one.
---> 55 _ = next(unconditional_samples)

    734   def __array__(self):
    735     raise NotImplementedError("Cannot convert a symbolic Tensor ({}) to a numpy"
--> 736                               " array.".format(self.name))
    737 
    738   def __len__(self):

NotImplementedError: Cannot convert a symbolic Tensor (transformer/add:0) to a numpy array.

I got those two bug when I try to use Generating Piano Music with Transformer for colab.  The code has already began with %tensorflow_version 1.x but it still can't run normally. I don't konw how to solve this problem and hope to get help.

**Comment by iansimon** [comment]
Annoyingly, you now need to downgrade numpy in order to make the notebook work.  We'll update the notebook soon, but for now you can add a cell before the first first cell that looks like:

```!pip uninstall -y numpy
!pip install numpy==1.19
```

After running that cell you will be prompted to (and must) restart the runtime.  Then, all the subsequent cells should work as is.

**Comment by shxluo** [comment]
It's working right now! Thanks A Lot!



---Original---
From: "Ian ***@***.***&gt;
Date: Tue, Apr 12, 2022 05:32 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [magenta/magenta] Generating Piano Music with Transformer forcolab bug (Issue #1988)




 
Annoyingly, you now need to downgrade numpy in order to make the notebook work.  We'll update the notebook soon, but for now you can add a cell before the first first cell that looks like:
 !pip install numpy==1.19  
After running that cell you will be prompted to (and must) restart the runtime.  Then, all the subsequent cells should work as is.
