### ISSUE TITLE
Magenta installation issue

### ISSUE THREAD

**Issue by suvigyajain0101** [magenta/magenta#2008]
pip install magenta or pip install -qU magenta is taking over an hour to run. Is it expected?

I'm trying to run the commands in Colab as mentioned in the docs - 
https://colab.research.google.com/notebooks/magenta/hello_magenta/hello_magenta.ipynb

Something to do with the new pip/python version?

==========================================================
Part of the output when ran the command - pip install -qU magenta

     |████████████████████████████████| 1.4 MB 4.6 MB/s 
     |████████████████████████████████| 3.6 MB 28.4 MB/s 
     |████████████████████████████████| 1.6 MB 40.5 MB/s 
     |████████████████████████████████| 2.3 MB 46.2 MB/s 
     |████████████████████████████████| 254 kB 46.2 MB/s 
     |████████████████████████████████| 1.4 MB 10.9 MB/s 
     |████████████████████████████████| 69 kB 6.1 MB/s 
     |████████████████████████████████| 352 kB 24.4 MB/s 
     |████████████████████████████████| 204 kB 16.6 MB/s 
     |████████████████████████████████| 90 kB 9.3 MB/s 
     |████████████████████████████████| 209 kB 53.6 MB/s 
     |████████████████████████████████| 5.6 MB 29.2 MB/s 
     |████████████████████████████████| 20.2 MB 1.1 MB/s 
     |████████████████████████████████| 408 kB 66.7 MB/s 
     |████████████████████████████████| 981 kB 54.9 MB/s 
     |████████████████████████████████| 79 kB 8.0 MB/s 
     |████████████████████████████████| 5.8 MB 42.5 MB/s 
     |████████████████████████████████| 193 kB 53.8 MB/s 
     |████████████████████████████████| 58 kB 5.8 MB/s 
     |████████████████████████████████| 385 kB 47.2 MB/s 
     |████████████████████████████████| 1.1 MB 50.9 MB/s 
     |████████████████████████████████| 367 kB 58.8 MB/s 
     |████████████████████████████████| 251 kB 55.8 MB/s 
     |████████████████████████████████| 114 kB 54.8 MB/s 
     |████████████████████████████████| 2.9 MB 37.3 MB/s 
     |████████████████████████████████| 191 kB 56.8 MB/s 
     |████████████████████████████████| 191 kB 56.7 MB/s 
     |████████████████████████████████| 178 kB 55.1 MB/s 
     |████████████████████████████████| 511.7 MB 5.6 kB/s 
     |████████████████████████████████| 1.6 MB 42.5 MB/s 
     |████████████████████████████████| 438 kB 57.3 MB/s 
     |████████████████████████████████| 511.7 MB 4.6 kB/s 
     |████████████████████████████████| 5.8 MB 55.0 MB/s 
     |████████████████████████████████| 5.8 MB 25.2 MB/s 
     |████████████████████████████████| 50 kB 6.4 MB/s 
     |████████████████████████████████| 48 kB 5.5 MB/s 
     |████████████████████████████████| 48 kB 4.9 MB/s 
     |████████████████████████████████| 48 kB 5.0 MB/s 
     |████████████████████████████████| 48 kB 5.4 MB/s 
     |████████████████████████████████| 48 kB 3.2 MB/s 
     |████████████████████████████████| 48 kB 4.8 MB/s 
     |████████████████████████████████| 48 kB 5.3 MB/s 
     |████████████████████████████████| 47 kB 4.2 MB/s 
     |████████████████████████████████| 47 kB 4.8 MB/s 
     |████████████████████████████████| 47 kB 4.9 MB/s 
     |████████████████████████████████| 47 kB 3.7 MB/s 
     |████████████████████████████████| 47 kB 4.3 MB/s 
     |████████████████████████████████| 44 kB 2.6 MB/s 
     |████████████████████████████████| 44 kB 2.4 MB/s 
     |████████████████████████████████| 43 kB 1.9 MB/s 
     |████████████████████████████████| 108 kB 49.1 MB/s 
     |████████████████████████████████| 107 kB 52.0 MB/s 
     |████████████████████████████████| 107 kB 52.0 MB/s 
     |████████████████████████████████| 103 kB 56.9 MB/s 
     |████████████████████████████████| 101 kB 10.6 MB/s 
     |████████████████████████████████| 89 kB 8.3 MB/s 
     |████████████████████████████████| 84 kB 3.6 MB/s 
     |████████████████████████████████| 78 kB 6.5 MB/s 
     |████████████████████████████████| 75 kB 3.8 MB/s 
     |████████████████████████████████| 73 kB 1.7 MB/s 
     |████████████████████████████████| 66 kB 4.3 MB/s 
     |████████████████████████████████| 365 kB 52.5 MB/s 
     |████████████████████████████████| 78 kB 6.9 MB/s 
WARNING: Discarding https://files.pythonhosted.org/packages/13/ee/eb8413c7e46f2dc110454e366b3ccf39e6db765749c8daf01a625c33323f/promise-0.2.2.tar.gz#sha256=1fb52a23bee47644819c4a11b0b7169474625c44629f9b76a04cf59e118f4f6c (from https://pypi.org/simple/promise/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: Discarding https://files.pythonhosted.org/packages/f6/07/fcd91d39d6f80c4c9a314efa28dbff33c91ef9aaf94169bcee09aa70d50f/promise-0.2.1.tar.gz#sha256=edbc51aa90318c9157f980b715e614543c863b86add41be70885c649cceef343 (from https://pypi.org/simple/promise/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: Discarding https://files.pythonhosted.org/packages/96/22/7ab1480ca9de349c380a4fbdf1a1ebcbfe2adef5a6183a26a0a9d88b8c6c/promise-0.2.0.tar.gz#sha256=bd8c3ed58092547c19bf5d321a5a6eb574e8327ff7c9e7b30b463beb54f5cb84 (from https://pypi.org/simple/promise/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: Discarding https://files.pythonhosted.org/packages/2c/be/f9e01d392107df0e35f88c1d3ca4d9994a84d962214fe155c72bebe1e851/promise-0.1.0.tar.gz#sha256=c2da3af5f1695077a8c130e5f05f308afae5030343925be2bdc9cffad995d678 (from https://pypi.org/simple/promise/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /packages/d0/c5/a934790953d9355e64bfa4419a9111772ecc9337afd44fee41af1de18c7b/importlib_resources-3.1.0-py2.py3-none-any.whl
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 77 kB 3.7 MB/s 
     |████████████████████████████████| 88 kB 6.7 MB/s 
     |████████████████████████████████| 74 kB 2.8 MB/s 
     |████████████████████████████████| 95 kB 4.8 MB/s

**Comment by suvigyajain0101** [comment]
Had to terminate after runnning ~3 hours - 

<img width="717" alt="image" src="https://user-images.githubusercontent.com/42478893/181384082-96fad6d9-e224-4b26-ab82-a5db83b2d9ae.png">

**Comment by Mannerow** [comment]
Try this instead: 

`!pip install -qU magenta==2.1.0`

It still takes longer than it should, but it works for me. Using the latest version of magenta worked fine for me up until about 2 weeks ago.

**Comment by suvigyajain0101** [comment]
Yes, it worked. Took about 15 min, but completed successfully!
