### ISSUE TITLE
Processed XX inputs total. Produced 0 outputs. (no clear fix)

### ISSUE THREAD

**Issue by Jovonni** [magenta/magenta#994]
**Problem Backgroud**
I have seen multiple people asking online, and getting different responses from people. One thread talks about changing the min_bar and min_unique_pitches parameters in the respective create_dataset model file.

Another thread also mentions altering the max_steps parameters to not skip certain midi files. However, it isn't quite clear as to what the actual problem is (without having to read through all of the models code, and diagnose myself).

**Question to answer**
What are the underlying reasons as to why certain .mid files get skipped, and other not?

**[Example output]**
INFO:tensorflow:Processed 65 inputs total. Produced 0 outputs.
INFO:tensorflow:DAGPipeline_DrumsExtractor_eval_drum_track_lengths_in_bars:

INFO:tensorflow:DAGPipeline_DrumsExtractor_eval_drum_tracks_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_DrumsExtractor_eval_drum_tracks_discarded_too_short: 0
INFO:tensorflow:DAGPipeline_DrumsExtractor_eval_drum_tracks_truncated: 0
INFO:tensorflow:DAGPipeline_DrumsExtractor_training_drum_track_lengths_in_bars:

INFO:tensorflow:DAGPipeline_DrumsExtractor_training_drum_tracks_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_DrumsExtractor_training_drum_tracks_discarded_too_short: 0
INFO:tensorflow:DAGPipeline_DrumsExtractor_training_drum_tracks_truncated: 0
INFO:tensorflow:DAGPipeline_RandomPartition_eval_drum_tracks_count: 4
INFO:tensorflow:DAGPipeline_RandomPartition_training_drum_tracks_count: 61

Usually, one of the above DAGPipeline log tells me what causes a skip, regardless on the model used (drum melody_rnn, etc). 

Any Thoughts?

**Comment by Jovonni** [comment]
Also to mention my hypotheses are monophonic vs polyphonic midis, aside from the normal flags used

**Comment by mattboch** [comment]
I'm having the same issue. 

**[Example Output]**
Completed.

INFO:tensorflow:Processed 2122 inputs total. Produced 0 outputs.
INFO:tensorflow:DAGPipeline_DrumsExtractor_eval_drum_track_lengths_in_bars:

INFO:tensorflow:DAGPipeline_DrumsExtractor_eval_drum_tracks_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_DrumsExtractor_eval_drum_tracks_discarded_too_short: 0
INFO:tensorflow:DAGPipeline_DrumsExtractor_eval_drum_tracks_truncated: 0
INFO:tensorflow:DAGPipeline_DrumsExtractor_training_drum_track_lengths_in_bars:

INFO:tensorflow:DAGPipeline_DrumsExtractor_training_drum_tracks_discarded_too_long: 0
INFO:tensorflow:DAGPipeline_DrumsExtractor_training_drum_tracks_discarded_too_short: 0
INFO:tensorflow:DAGPipeline_DrumsExtractor_training_drum_tracks_truncated: 0
INFO:tensorflow:DAGPipeline_RandomPartition_eval_drum_tracks_count: 214
INFO:tensorflow:DAGPipeline_RandomPartition_training_drum_tracks_count: 1908

**Comment by LinHuiqing** [comment]
I'm facing the same issue as well. I see the following warnings before the output INFO lines as well.
```
WARNING:tensorflow:From <path to anaconda>/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From <path to repo>/magenta/magenta/pipelines/pipeline.py:310: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
W1123 23:14:42.132252 140004163573568 deprecation.py:323] From <path to repo>/magenta/magenta/pipelines/pipeline.py:310: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
```

**Comment by LinHuiqing** [comment]
Ran the test script which gave the following output:
```
2020-11-23 23:14:16.732609: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From <path to anaconda>/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Running tests under Python 3.7.9: <path to anaconda>/anaconda3/envs/magenta/bin/python
[ RUN      ] MelodyRNNPipelineTest.testMelodyRNNPipeline
INFO:tensorflow:time(__main__.MelodyRNNPipelineTest.testMelodyRNNPipeline): 0.01s
I1123 23:14:19.222388 139634966488896 test_util.py:1973] time(__main__.MelodyRNNPipelineTest.testMelodyRNNPipeline): 0.01s
[       OK ] MelodyRNNPipelineTest.testMelodyRNNPipeline
[ RUN      ] MelodyRNNPipelineTest.test_session
[  SKIPPED ] MelodyRNNPipelineTest.test_session
----------------------------------------------------------------------
Ran 2 tests in 0.014s

OK (skipped=1)
```
Any ideas as to how we can overcome this? Thanks in advance!

**Comment by LinHuiqing** [comment]
[solved] 
For my case, it was because I was trying to pre-process polyphonic data (Maestro) for a monophonic model (Melody RNN). Do take note of the type of model you are using - polyphonic vs monophonic, or whether the instrument should be a drum. 
Hope this helps!
